CREATE OR REPLACE WAREHOUSE Health_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
    CREATE OR REPLACE DATABASE Health_DW;
CREATE OR REPLACE SCHEMA Snowflake_SCHEMA;

USE SCHEMA Snowflake_SCHEMA;
CREATE OR REPLACE STAGE HEALTHCARE_STAGE;
show stages

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER=1
TRIM_SPACE=TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE;

CREATE OR REPLACE TABLE STG_PATIENTS (
    PATIENT_ID VARCHAR,
    PATIENT_NAME VARCHAR,
    GENDER VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR
);

CREATE OR REPLACE TABLE STG_DOCTORS (
    DOCTOR_ID VARCHAR,
    DOCTOR_NAME VARCHAR,
    SPECIALIZATION VARCHAR
);

CREATE OR REPLACE TABLE STG_HOSPITALS (
    HOSPITAL_ID VARCHAR,
    HOSPITAL_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    REGION VARCHAR
);

CREATE OR REPLACE TABLE STG_DEPARTMENTS (
    DEPARTMENT_ID VARCHAR,
    DEPARTMENT_NAME VARCHAR
);

CREATE OR REPLACE TABLE STG_TREATMENTS (
    TREATMENT_ID VARCHAR,
    TREATMENT_NAME VARCHAR,
    TREATMENT_CATEGORY VARCHAR
);

CREATE OR REPLACE TABLE STG_ADMISSIONS (
    ADMISSION_ID VARCHAR,
    PATIENT_ID VARCHAR,
    DOCTOR_ID VARCHAR,
    HOSPITAL_ID VARCHAR,
    DEPARTMENT_ID VARCHAR,
    ADMISSION_DATE DATE,
    DISCHARGE_DATE DATE
);



