CREATE OR REPLACE WAREHOUSE ECOMMERCE_19B_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE HEALTHCARE_19B_DW;

CREATE OR REPLACE SCHEMA HEALTHCARE_19B_DW.HEALTHCARE_SCHEMA;

USE DATABASE HEALTHCARE_19B_DW;

USE SCHEMA HEALTHCARE_SCHEMA;



CREATE OR REPLACE TABLE RAW_DOCTOR_ROSTER (
    SHIFT_DATE DATE,
    DOCTOR_ID VARCHAR,
    DEPARTMENT_ID VARCHAR,
    SHIFT_TYPE VARCHAR
);

INSERT INTO RAW_DOCTOR_ROSTER
VALUES
('2026-08-20', 'DOC-01', 'DEP-10', 'MORNING'),
('2026-08-20', 'DOC-02', 'DEP-10', 'NIGHT'),
('2026-08-20', 'DOC-03', 'DEP-20', 'MORNING'),
('2026-08-21', 'DOC-01', 'DEP-10', 'NIGHT'),
('2026-08-21', 'DOC-04', 'DEP-30', 'MORNING'),
('2026-08-21', 'DOC-02', 'DEP-10', 'MORNING');


CREATE OR REPLACE TABLE RAW_PATIENT_JOURNEY (
    ENCOUNTER_ID VARCHAR,
    PATIENT_ID VARCHAR,
    TRIAGE_DATE DATE,
    ADMISSION_DATE DATE,
    DISCHARGE_DATE DATE
);

INSERT INTO RAW_PATIENT_JOURNEY
VALUES
('ENC-701', 'PAT-901', '2026-08-15', '2026-08-15', '2026-08-18'),
('ENC-702', 'PAT-902', '2026-08-16', '2026-08-17', '2026-08-22'),
('ENC-703', 'PAT-903', '2026-08-18', '2026-08-18', NULL),
('ENC-704', 'PAT-904', '2026-08-19', '2026-08-20', '2026-08-21'),
('ENC-705', 'PAT-905', '2026-08-20', NULL, NULL);



CREATE OR REPLACE TABLE RAW_TREATMENT_BILLS (
    CLAIM_ID VARCHAR,
    ENCOUNTER_ID VARCHAR,
    PATIENT_ID VARCHAR,
    PROCEDURE_COST NUMBER(12,2),
    INSURANCE_DISCOUNT_PCT NUMBER(5,4),
    COPAY_AMOUNT NUMBER(12,2)
);

INSERT INTO RAW_TREATMENT_BILLS
VALUES
('CLM-301', 'ENC-701', 'PAT-901',  5000.00, 0.10, 200.00),
('CLM-302', 'ENC-702', 'PAT-902', 12000.00, 0.15, 500.00),
('CLM-303', 'ENC-702', 'PAT-902',  3500.00, 0.00, 100.00),
('CLM-304', 'ENC-704', 'PAT-904',   800.00, 0.05,  50.00);


-- TASK 1
-- FACTLESS STAFF COVERAGE

CREATE OR REPLACE TABLE FACTLESS_STAFF_COVERAGE (
    SHIFT_DATE DATE,
    DOCTOR_ID VARCHAR,
    DEPARTMENT_ID VARCHAR,
    SHIFT_TYPE VARCHAR
);

INSERT INTO FACTLESS_STAFF_COVERAGE
SELECT
    SHIFT_DATE,
    DOCTOR_ID,
    DEPARTMENT_ID,
    SHIFT_TYPE
FROM RAW_DOCTOR_ROSTER;


-- Validate Task 1

SELECT
    COUNT(*) AS TOTAL_ROSTER_ROWS
FROM FACTLESS_STAFF_COVERAGE;


-- TASK 2
-- DEPARTMENTS WITH ZERO NIGHT SHIFTS


WITH DEPARTMENTS AS (
    SELECT DISTINCT
        DEPARTMENT_ID
    FROM FACTLESS_STAFF_COVERAGE
),

NIGHT_SHIFTS AS (
    SELECT
        DEPARTMENT_ID,
        COUNT(*) AS NIGHT_SHIFT_COUNT

    FROM FACTLESS_STAFF_COVERAGE

    WHERE SHIFT_DATE = '2026-08-20'
      AND SHIFT_TYPE = 'NIGHT'

    GROUP BY DEPARTMENT_ID
)

SELECT
    d.DEPARTMENT_ID,

    COALESCE(
        n.NIGHT_SHIFT_COUNT,
        0
    ) AS NIGHT_SHIFT_COUNT

FROM DEPARTMENTS d

LEFT JOIN NIGHT_SHIFTS n
    ON d.DEPARTMENT_ID = n.DEPARTMENT_ID

WHERE COALESCE(n.NIGHT_SHIFT_COUNT, 0) = 0

ORDER BY d.DEPARTMENT_ID;

-- TASK 3
-- PATIENT ADMISSION ACCUMULATING SNAPSHOT

CREATE OR REPLACE TABLE FACT_PATIENT_ADMISSION_LIFECYCLE (
    ENCOUNTER_ID VARCHAR,
    PATIENT_ID VARCHAR,
    TRIAGE_DATE DATE,
    ADMISSION_DATE DATE,
    DISCHARGE_DATE DATE,
    TRIAGE_TO_ADMIT_DAYS NUMBER,
    LENGTH_OF_STAY_DAYS NUMBER
);


INSERT INTO FACT_PATIENT_ADMISSION_LIFECYCLE
SELECT
    ENCOUNTER_ID,
    PATIENT_ID,
    TRIAGE_DATE,
    ADMISSION_DATE,
    DISCHARGE_DATE,

    DATEDIFF(
        DAY,
        TRIAGE_DATE,
        ADMISSION_DATE
    ) AS TRIAGE_TO_ADMIT_DAYS,

    DATEDIFF(
        DAY,
        ADMISSION_DATE,
        DISCHARGE_DATE
    ) AS LENGTH_OF_STAY_DAYS

FROM RAW_PATIENT_JOURNEY;


-- Validate Task 3

SELECT
    ENCOUNTER_ID,
    PATIENT_ID,
    TRIAGE_TO_ADMIT_DAYS,
    LENGTH_OF_STAY_DAYS

FROM FACT_PATIENT_ADMISSION_LIFECYCLE

WHERE LENGTH_OF_STAY_DAYS IS NOT NULL

ORDER BY ENCOUNTER_ID;

-- TASK 4
-- TREATMENT BILLING TRANSACTION FACT

CREATE OR REPLACE TABLE FACT_TREATMENT_BILLING (
    CLAIM_ID VARCHAR,
    ENCOUNTER_ID VARCHAR,
    PATIENT_ID VARCHAR,
    PROCEDURE_COST NUMBER(12,2),
    INSURANCE_DISCOUNT_PCT NUMBER(5,4),
    COPAY_AMOUNT NUMBER(12,2),
    NET_CHARGE NUMBER(12,2)
);


INSERT INTO FACT_TREATMENT_BILLING
SELECT
    CLAIM_ID,
    ENCOUNTER_ID,
    PATIENT_ID,
    PROCEDURE_COST,
    INSURANCE_DISCOUNT_PCT,
    COPAY_AMOUNT,

    (
        PROCEDURE_COST *
        (1 - INSURANCE_DISCOUNT_PCT)
    ) - COPAY_AMOUNT AS NET_CHARGE

FROM RAW_TREATMENT_BILLS;


-- Validate Task 4

SELECT
    CLAIM_ID,
    ENCOUNTER_ID,
    PROCEDURE_COST,
    COPAY_AMOUNT,
    NET_CHARGE

FROM FACT_TREATMENT_BILLING

ORDER BY CLAIM_ID;

-- TASK 5
-- BILLING AGGREGATION

SELECT
    ENCOUNTER_ID,

    SUM(NET_CHARGE) AS TOTAL_NET_CHARGES,

    AVG(PROCEDURE_COST) AS AVG_PROCEDURE_COST

FROM FACT_TREATMENT_BILLING

GROUP BY ENCOUNTER_ID

ORDER BY ENCOUNTER_ID;

-- TASK 6
-- AUDIT ZERO-CLAIM ENCOUNTERS

SELECT
    p.ENCOUNTER_ID,
    p.PATIENT_ID,

    'NO_CLAIMS_ISSUED' AS UNBILLED_STATUS

FROM FACT_PATIENT_ADMISSION_LIFECYCLE p

LEFT JOIN FACT_TREATMENT_BILLING b
    ON p.ENCOUNTER_ID = b.ENCOUNTER_ID

WHERE b.CLAIM_ID IS NULL

ORDER BY p.ENCOUNTER_ID;