CREATE OR REPLACE WAREHOUSE  COMPUTE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE HEALTHCARE_PIPELINE_DB;
USE DATABASE HEALTHCARE_PIPELINE_DB;

CREATE OR REPLACE SCHEMA HEALTHCARE_PIPELINE_DB.CLAIMS_CORE;
USE SCHEMA HEALTHCARE_PIPELINE_DB.CLAIMS_CORE;

--- INGESTION OF THE  RAW DATA  WCHI SIS IN THE JSON FORMAT 
-- APPLYING MEDALIAN ARCHITECTURE
CREATE OR REPLACE TABLE BRONZE_RAW_CLAIMS
(
    INGEST_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PAYLOAD VARIANT,
    LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW_CLAIMS_LANDING
(
    RAW_RECORD_TEXT STRING,
    BATCH_NUMBER NUMBER,
    RECEIVED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- INSERING THE BATCH WISE DATA INTO FIRST LEVEL
INSERT INTO RAW_CLAIMS_LANDING
(
    RAW_RECORD_TEXT,
    BATCH_NUMBER
)
SELECT
    COLUMN1,
    1
FROM VALUES

('{"claim_id":"CLM-301","submitted_at":"2026-08-10T08:00:00Z","patient_id":5001,"provider_id":"PRV-10","diagnosis_code":"ICD-10-A","billed_amount":15000.00,"copay_amount":500.00,"status":"PENDING"}'),

('{"claim_id":"CLM-302","submitted_at":"2026-08-10T08:15:00Z","patient_id":5002,"provider_id":"PRV-11","diagnosis_code":"ICD-10-B","billed_amount":8500.00,"copay_amount":300.00,"status":"APPROVED"}'),

('{"claim_id":"CLM-303","submitted_at":"2026-08-10T08:30:00Z","patient_id":5003,"provider_id":"PRV-10","diagnosis_code":"ICD-10-C","billed_amount":45000.00,"copay_amount":1500.00,"status":"PENDING"}'),

('{"claim_id":"CLM-304","submitted_at":"2026-08-10T09:00:00Z","patient_id":5004,"provider_id":"PRV-12","diagnosis_code":"ICD-10-A","billed_amount":3200.00,"copay_amount":100.00,"status":"APPROVED"}');


INSERT INTO RAW_CLAIMS_LANDING
(
    RAW_RECORD_TEXT,
    BATCH_NUMBER
)
SELECT
    COLUMN1,
    2
FROM VALUES

('{"claim_id":"CLM-301","submitted_at":"2026-08-10T08:00:00Z","patient_id":5001,"provider_id":"PRV-10","diagnosis_code":"ICD-10-A","billed_amount":15000.00,"copay_amount":500.00,"status":"APPROVED"}'),

('{"claim_id":"CLM-303","submitted_at":"2026-08-10T08:30:00Z","patient_id":5003,"provider_id":"PRV-10","diagnosis_code":"ICD-10-C","billed_amount":45000.00,"copay_amount":1500.00,"status":"DENIED"}'),

('{"claim_id":"CLM-305","submitted_at":"2026-08-10T10:00:00Z","patient_id":5005,"provider_id":"PRV-11","diagnosis_code":"ICD-10-B","billed_amount":120000.00,"copay_amount":2500.00,"status":"APPROVED"}');

INSERT INTO RAW_CLAIMS_LANDING
(
    RAW_RECORD_TEXT,
    BATCH_NUMBER
)
SELECT
    COLUMN1,
    3
FROM VALUES

('{"claim_id":"CLM-306","submitted_at":"2026-08-10T10:30:00Z","patient_id":5002,"provider_id":"PRV-12","diagnosis_code":"ICD-10-A","billed_amount":6000.00,"copay_amount":200.00,"status":"APPROVED"}'),

('INVALID_PAYLOAD_UNPARSEABLE_STRING');



SELECT
    COUNT(*) AS TOTAL_RAW_RECORDS
FROM RAW_CLAIMS_LANDING;

--- HANDLING THE ERROR BY CRATING SEPATE QUARARITINE TABLE
CREATE OR REPLACE TABLE QUARANTINE_CLAIMS_PAYLOADS
(
    QUARANTINE_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    RAW_RECORD_TEXT STRING,
    REASON STRING
);

INSERT INTO QUARANTINE_CLAIMS_PAYLOADS
(
    RAW_RECORD_TEXT,
    REASON
)
SELECT
    RAW_RECORD_TEXT,
    'MALFORMED_JSON_BODY'
FROM RAW_CLAIMS_LANDING
WHERE TRY_PARSE_JSON(RAW_RECORD_TEXT) IS NULL;

SELECT
    QUARANTINE_ID,
    RAW_RECORD_TEXT,
    REASON
FROM QUARANTINE_CLAIMS_PAYLOADS
ORDER BY QUARANTINE_ID;

INSERT INTO BRONZE_RAW_CLAIMS
(
    PAYLOAD
)
SELECT
    TRY_PARSE_JSON(RAW_RECORD_TEXT)
FROM RAW_CLAIMS_LANDING
WHERE TRY_PARSE_JSON(RAW_RECORD_TEXT) IS NOT NULL;

-- VERIFYING THE BRONZE LAYER
SELECT
    INGEST_ID,
    PAYLOAD:claim_id::STRING AS CLAIM_ID,
    PAYLOAD:status::STRING AS STATUS,
    LOADED_AT
FROM BRONZE_RAW_CLAIMS
ORDER BY INGEST_ID;

--- TASK 3 Snowflake Stream
DROP TABLE IF EXISTS BRONZE_RAW_CLAIMS;

CREATE TABLE BRONZE_RAW_CLAIMS
(
    INGEST_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PAYLOAD VARIANT,
    LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE STREAM STRM_BRONZE_CLAIMS
ON TABLE BRONZE_RAW_CLAIMS
APPEND_ONLY = TRUE;

INSERT INTO BRONZE_RAW_CLAIMS
(
    PAYLOAD
)
SELECT
    TRY_PARSE_JSON(RAW_RECORD_TEXT)
FROM RAW_CLAIMS_LANDING
WHERE TRY_PARSE_JSON(RAW_RECORD_TEXT) IS NOT NULL;

SELECT
    INGEST_ID,
    PAYLOAD:claim_id::STRING AS CLAIM_ID,
    PAYLOAD:status::STRING AS STATUS,
    METADATA$ACTION,
    METADATA$ISUPDATE
FROM STRM_BRONZE_CLAIMS
ORDER BY INGEST_ID;

-- CREATING THE SILVER LAYER
CREATE OR REPLACE TABLE SILVER_CLAIMS_TRANSACTIONS
(
    CLAIM_ID STRING,
    SUBMITTED_AT TIMESTAMP_TZ,
    PATIENT_ID NUMBER,
    PROVIDER_ID STRING,
    DIAGNOSIS_CODE STRING,
    BILLED_AMOUNT NUMBER(18,2),
    COPAY_AMOUNT NUMBER(18,2),
    NET_PAYABLE_AMOUNT NUMBER(18,2),
    STATUS STRING
);


MERGE INTO SILVER_CLAIMS_TRANSACTIONS AS TARGET

USING
(
    SELECT
        PAYLOAD:claim_id::STRING AS CLAIM_ID,
        PAYLOAD:submitted_at::TIMESTAMP_TZ AS SUBMITTED_AT,
        PAYLOAD:patient_id::NUMBER AS PATIENT_ID,
        PAYLOAD:provider_id::STRING AS PROVIDER_ID,
        PAYLOAD:diagnosis_code::STRING AS DIAGNOSIS_CODE,
        PAYLOAD:billed_amount::NUMBER(18,2) AS BILLED_AMOUNT,
        PAYLOAD:copay_amount::NUMBER(18,2) AS COPAY_AMOUNT,
        (
            PAYLOAD:billed_amount::NUMBER(18,2)
            -
            PAYLOAD:copay_amount::NUMBER(18,2)
        ) AS NET_PAYABLE_AMOUNT,
        PAYLOAD:status::STRING AS STATUS
    FROM
    (
        SELECT
            *,
            ROW_NUMBER() OVER
            (
                PARTITION BY PAYLOAD:claim_id::STRING
                ORDER BY INGEST_ID DESC
            ) AS RN
        FROM STRM_BRONZE_CLAIMS
        WHERE METADATA$ACTION = 'INSERT'
    )
    WHERE RN = 1
) AS SOURCE

ON TARGET.CLAIM_ID = SOURCE.CLAIM_ID

WHEN MATCHED THEN UPDATE SET
    TARGET.SUBMITTED_AT = SOURCE.SUBMITTED_AT,
    TARGET.PATIENT_ID = SOURCE.PATIENT_ID,
    TARGET.PROVIDER_ID = SOURCE.PROVIDER_ID,
    TARGET.DIAGNOSIS_CODE = SOURCE.DIAGNOSIS_CODE,
    TARGET.BILLED_AMOUNT = SOURCE.BILLED_AMOUNT,
    TARGET.COPAY_AMOUNT = SOURCE.COPAY_AMOUNT,
    TARGET.NET_PAYABLE_AMOUNT = SOURCE.NET_PAYABLE_AMOUNT,
    TARGET.STATUS = SOURCE.STATUS

WHEN NOT MATCHED THEN INSERT
(
    CLAIM_ID,
    SUBMITTED_AT,
    PATIENT_ID,
    PROVIDER_ID,
    DIAGNOSIS_CODE,
    BILLED_AMOUNT,
    COPAY_AMOUNT,
    NET_PAYABLE_AMOUNT,
    STATUS
)
VALUES
(
    SOURCE.CLAIM_ID,
    SOURCE.SUBMITTED_AT,
    SOURCE.PATIENT_ID,
    SOURCE.PROVIDER_ID,
    SOURCE.DIAGNOSIS_CODE,
    SOURCE.BILLED_AMOUNT,
    SOURCE.COPAY_AMOUNT,
    SOURCE.NET_PAYABLE_AMOUNT,
    SOURCE.STATUS
);


SELECT
    CLAIM_ID,
    PATIENT_ID,
    PROVIDER_ID,
    DIAGNOSIS_CODE,
    BILLED_AMOUNT,
    COPAY_AMOUNT,
    NET_PAYABLE_AMOUNT,
    STATUS
FROM SILVER_CLAIMS_TRANSACTIONS
ORDER BY CLAIM_ID;

--TASK 4 — Dynamic Table
CREATE OR REPLACE DYNAMIC TABLE DT_PROVIDER_FINANCIAL_SUMMARY
(
    PROVIDER_ID,
    TOTAL_BILLED_AMOUNT,
    TOTAL_COPAY_COLLECT,
    TOTAL_NET_PAYABLE,
    APPROVED_CLAIMS
)
TARGET_LAG = '1 minute'
WAREHOUSE = COMPUTE_WH
REFRESH_MODE = INCREMENTAL
AS
SELECT
    PROVIDER_ID,
    SUM(BILLED_AMOUNT) AS TOTAL_BILLED_AMOUNT,
    SUM(COPAY_AMOUNT) AS TOTAL_COPAY_COLLECT,
    SUM(NET_PAYABLE_AMOUNT) AS TOTAL_NET_PAYABLE,
    COUNT(*) AS APPROVED_CLAIMS
FROM SILVER_CLAIMS_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY PROVIDER_ID;

SELECT
    PROVIDER_ID,
    TOTAL_BILLED_AMOUNT,
    TOTAL_COPAY_COLLECT,
    TOTAL_NET_PAYABLE,
    APPROVED_CLAIMS
FROM DT_PROVIDER_FINANCIAL_SUMMARY
ORDER BY PROVIDER_ID;


---TASK 5 — Dynamic Table Refresh Monitoring

SELECT
    NAME AS DYNAMIC_TABLE_NAME,
    REFRESH_ACTION,
    CASE
        WHEN REFRESH_ACTION = 'INCREMENTAL'
            THEN 'INCREMENTAL'
        WHEN REFRESH_ACTION = 'FULL'
            THEN 'FULL'
        ELSE REFRESH_ACTION
    END AS REFRESH_MODE,
    CASE
        WHEN STATE = 'SUCCEEDED'
            THEN 'SUCCESS'
        ELSE STATE
    END AS QUALIFIED_STATUS,
    REFRESH_TRIGGER,
    REFRESH_START_TIME,
    REFRESH_END_TIME
FROM TABLE
(
    INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY
    (
        NAME => 'HEALTHCARE_PIPELINE_DB.CLAIMS_CORE.DT_PROVIDER_FINANCIAL_SUMMARY',
        RESULT_LIMIT => 100
    )
)
ORDER BY REFRESH_START_TIME DESC;

----TASK 6 — End-to-End Reconciliation
SELECT
    SUM(PAYLOAD:billed_amount::NUMBER(18,2)) AS BRONZE_GROSS_TOTAL
FROM BRONZE_RAW_CLAIMS;

--Final Reconciliation Query


WITH BRONZE_TOTAL AS
(
    SELECT
        SUM(PAYLOAD:billed_amount::NUMBER(18,2))
        AS BRONZE_GROSS_TOTAL
    FROM BRONZE_RAW_CLAIMS
),

SILVER_TOTAL AS
(
    SELECT
        SUM(BILLED_AMOUNT)
        AS SILVER_GROSS_TOTAL
    FROM SILVER_CLAIMS_TRANSACTIONS
),

GOLD_TOTAL AS
(
    SELECT
        SUM(TOTAL_BILLED_AMOUNT)
        AS GOLD_GROSS_TOTAL
    FROM DT_PROVIDER_FINANCIAL_SUMMARY
)

SELECT
    BRONZE_GROSS_TOTAL,
    SILVER_GROSS_TOTAL,
    GOLD_GROSS_TOTAL,

    CASE
        WHEN BRONZE_GROSS_TOTAL = 257700.00
         AND SILVER_GROSS_TOTAL = 197700.00
         AND GOLD_GROSS_TOTAL = 152700.00
        THEN TRUE
        ELSE FALSE
    END AS RECONCILED_FLAG

FROM BRONZE_TOTAL
CROSS JOIN SILVER_TOTAL
CROSS JOIN GOLD_TOTAL;

