CREATE OR REPLACE WAREHOUSE CUSTOMER_HISTORY_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

create or replace database CUSTOMER_PROFILE5_DB;
CREATE OR REPLACE SCHEMA CUSTOMER_PROFILE5_DB.SCD_SCHEMA;
USE DATABASE CUSTOMER_PROFILE5_DB;
USE SCHEMA SCD_SCHEMA;
CREATE OR REPLACE STAGE CUSTOMER_STAGE;
show stages;

CREATE OR REPLACE FILE FORMAT RETAIL_CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '');
show file formats;
CREATE OR REPLACE TABLE STG_REGIONS_STORES
(
    STORE_ID         NUMBER,
    STORE_NAME       VARCHAR(100),
    CITY             VARCHAR(50),
    STATE            VARCHAR(50),
    REGION_NAME      VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

CREATE OR REPLACE TABLE STG_PRODUCT_HIERARCHY
(
    PRODUCT_ID       NUMBER,
    PRODUCT_NAME     VARCHAR(100),
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_NAME    VARCHAR(50),
    UNIT_PRICE       NUMBER(10,2)
);

CREATE OR REPLACE TABLE STG_CUSTOMERS
(
    CUSTOMER_ID   NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY          VARCHAR(50),
    STATE         VARCHAR(50)
);

CREATE OR REPLACE TABLE STG_SALES_TRANSACTIONS
(
    TRANSACTION_ID   VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID      NUMBER,
    STORE_ID         NUMBER,
    PRODUCT_ID       NUMBER,
    QUANTITY         NUMBER,
    UNIT_PRICE       NUMBER(10,2)
);

--TASK 4 — Load Staging Tables Using COPY INTO
COPY INTO STG_REGIONS_STORES
FROM @CUSTOMER_STAGE/regions_and_stores.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

SELECT *
FROM STG_REGIONS_STORES
ORDER BY STORE_ID;

COPY INTO STG_PRODUCT_HIERARCHY
FROM @CUSTOMER_STAGE/product_hierarchy.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

select * from  STG_PRODUCT_HIERARCHY order by PRODUCT_ID;


COPY INTO STG_CUSTOMERS
FROM @CUSTOMER_STAGE/c1.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

select * from  STG_CUSTOMERS order by CUSTOMER_ID ;


COPY INTO STG_SALES_TRANSACTIONS
FROM @CUSTOMER_STAGE/sales_transactions.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

select * from   STG_SALES_TRANSACTIONS  order by  CUSTOMER_ID  ;


--TASK 5 — Create Denormalized Star Schema Store Dimension
CREATE OR REPLACE TABLE STAR_DIM_STORE
(
    STORE_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID         NUMBER,
    STORE_NAME       VARCHAR(100),
    CITY             VARCHAR(50),
    STATE            VARCHAR(50),
    REGION_NAME      VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);
INSERT INTO STAR_DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_NAME,
    REGIONAL_MANAGER
)
SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_NAME,
    REGIONAL_MANAGER
FROM STG_REGIONS_STORES;

SELECT *
FROM STAR_DIM_STORE
ORDER BY STORE_ID;

--TASK 6 — Create Denormalized Star Schema Product Dimension
CREATE OR REPLACE TABLE STAR_DIM_PRODUCT
(
    PRODUCT_KEY      NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID       NUMBER,
    PRODUCT_NAME     VARCHAR(100),
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_NAME    VARCHAR(50),
    UNIT_PRICE       NUMBER(10,2)
);

INSERT INTO STAR_DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    SUBCATEGORY_NAME,
    CATEGORY_NAME,
    UNIT_PRICE
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    SUBCATEGORY_NAME,
    CATEGORY_NAME,
    UNIT_PRICE
FROM STG_PRODUCT_HIERARCHY;

SELECT *
FROM STAR_DIM_PRODUCT
ORDER BY PRODUCT_ID;

--TASK 7 — Create and Load STAR_FACT_SALES
CREATE OR REPLACE TABLE STAR_FACT_SALES
(
    SALES_KEY       NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID  VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID     NUMBER,
    STORE_KEY       NUMBER,
    PRODUCT_KEY     NUMBER,
    QUANTITY        NUMBER,
    TOTAL_AMOUNT    NUMBER(12,2)
);

INSERT INTO STAR_FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_ID,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    s.TRANSACTION_ID,
    s.TRANSACTION_DATE,
    s.CUSTOMER_ID,
    ds.STORE_KEY,
    dp.PRODUCT_KEY,
    s.QUANTITY,
    s.QUANTITY * s.UNIT_PRICE
FROM STG_SALES_TRANSACTIONS s
JOIN STAR_DIM_STORE ds
    ON s.STORE_ID = ds.STORE_ID
JOIN STAR_DIM_PRODUCT dp
    ON s.PRODUCT_ID = dp.PRODUCT_ID;

SELECT *
FROM STAR_FACT_SALES
ORDER BY SALES_KEY;

---TASK 8 — Build Normalized Snowflake Store Hierarchy
CREATE OR REPLACE TABLE SNOW_DIM_REGION
(
    REGION_KEY       NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION_NAME      VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

CREATE OR REPLACE TABLE SNOW_DIM_STORE
(
    STORE_KEY  NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID   NUMBER,
    STORE_NAME VARCHAR(100),
    CITY       VARCHAR(50),
    STATE      VARCHAR(50),
    REGION_KEY NUMBER,

    CONSTRAINT FK_SNOW_STORE_REGION
        FOREIGN KEY (REGION_KEY)
        REFERENCES SNOW_DIM_REGION(REGION_KEY)
);

--TASK 9 — Populate Snowflake Store Hierarchy
INSERT INTO SNOW_DIM_REGION
(
    REGION_NAME,
    REGIONAL_MANAGER
)
SELECT DISTINCT
    REGION_NAME,
    REGIONAL_MANAGER
FROM STG_REGIONS_STORES;
SELECT *
FROM SNOW_DIM_REGION
ORDER BY REGION_KEY;

INSERT INTO SNOW_DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_KEY
)
SELECT
    s.STORE_ID,
    s.STORE_NAME,
    s.CITY,
    s.STATE,
    r.REGION_KEY
FROM STG_REGIONS_STORES s
JOIN SNOW_DIM_REGION r
    ON s.REGION_NAME = r.REGION_NAME;

--TASK 10 — Build Normalized Snowflake Product Hierarchy
CREATE OR REPLACE TABLE SNOW_DIM_CATEGORY
(
    CATEGORY_KEY  NUMBER AUTOINCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50)
);
CREATE OR REPLACE TABLE SNOW_DIM_SUBCATEGORY
(
    SUBCATEGORY_KEY  NUMBER AUTOINCREMENT PRIMARY KEY,
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_KEY     NUMBER,

    CONSTRAINT FK_SUBCATEGORY_CATEGORY
        FOREIGN KEY (CATEGORY_KEY)
        REFERENCES SNOW_DIM_CATEGORY(CATEGORY_KEY)
);
CREATE OR REPLACE TABLE SNOW_DIM_PRODUCT
(
    PRODUCT_KEY     NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID      NUMBER,
    PRODUCT_NAME    VARCHAR(100),
    UNIT_PRICE      NUMBER(10,2),
    SUBCATEGORY_KEY NUMBER,

    CONSTRAINT FK_PRODUCT_SUBCATEGORY
        FOREIGN KEY (SUBCATEGORY_KEY)
        REFERENCES SNOW_DIM_SUBCATEGORY(SUBCATEGORY_KEY)
);

--TASK 11 — Populate Snowflake Product Hierarchy
INSERT INTO SNOW_DIM_CATEGORY
(
    CATEGORY_NAME
)
SELECT DISTINCT
    CATEGORY_NAME
FROM STG_PRODUCT_HIERARCHY;

INSERT INTO SNOW_DIM_SUBCATEGORY
(
    SUBCATEGORY_NAME,
    CATEGORY_KEY
)
SELECT
    p.SUBCATEGORY_NAME,
    c.CATEGORY_KEY
FROM STG_PRODUCT_HIERARCHY p
JOIN SNOW_DIM_CATEGORY c
    ON p.CATEGORY_NAME = c.CATEGORY_NAME;
INSERT INTO SNOW_DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    UNIT_PRICE,
    SUBCATEGORY_KEY
)
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.UNIT_PRICE,
    sc.SUBCATEGORY_KEY
FROM STG_PRODUCT_HIERARCHY p
JOIN SNOW_DIM_SUBCATEGORY sc
    ON p.SUBCATEGORY_NAME = sc.SUBCATEGORY_NAME;

    --TASK 12 — Create and Load SNOW_FACT_SALES
    CREATE OR REPLACE TABLE SNOW_FACT_SALES
(
    SALES_KEY       NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID  VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID     NUMBER,
    STORE_KEY       NUMBER,
    PRODUCT_KEY     NUMBER,
    QUANTITY        NUMBER,
    TOTAL_AMOUNT    NUMBER(12,2),

    CONSTRAINT FK_SNOW_FACT_STORE
        FOREIGN KEY (STORE_KEY)
        REFERENCES SNOW_DIM_STORE(STORE_KEY),

    CONSTRAINT FK_SNOW_FACT_PRODUCT
        FOREIGN KEY (PRODUCT_KEY)
        REFERENCES SNOW_DIM_PRODUCT(PRODUCT_KEY)
);

INSERT INTO SNOW_FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_ID,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    s.TRANSACTION_ID,
    s.TRANSACTION_DATE,
    s.CUSTOMER_ID,
    ds.STORE_KEY,
    dp.PRODUCT_KEY,
    s.QUANTITY,
    s.QUANTITY * s.UNIT_PRICE
FROM STG_SALES_TRANSACTIONS s
JOIN SNOW_DIM_STORE ds
    ON s.STORE_ID = ds.STORE_ID
JOIN SNOW_DIM_PRODUCT dp
    ON s.PRODUCT_ID = dp.PRODUCT_ID;

--TASK 13 — Star Schema Analytics Query
SELECT
    ds.REGION_NAME,
    dp.CATEGORY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM STAR_FACT_SALES f
JOIN STAR_DIM_STORE ds
    ON f.STORE_KEY = ds.STORE_KEY
JOIN STAR_DIM_PRODUCT dp
    ON f.PRODUCT_KEY = dp.PRODUCT_KEY
GROUP BY
    ds.REGION_NAME,
    dp.CATEGORY_NAME
ORDER BY
    ds.REGION_NAME,
    dp.CATEGORY_NAME;

--TASK 14 — Snowflake Schema Analytics Query
SELECT
    r.REGION_NAME,
    c.CATEGORY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SNOW_FACT_SALES f

JOIN SNOW_DIM_STORE s
    ON f.STORE_KEY = s.STORE_KEY

JOIN SNOW_DIM_REGION r
    ON s.REGION_KEY = r.REGION_KEY

JOIN SNOW_DIM_PRODUCT p
    ON f.PRODUCT_KEY = p.PRODUCT_KEY

JOIN SNOW_DIM_SUBCATEGORY sc
    ON p.SUBCATEGORY_KEY = sc.SUBCATEGORY_KEY

JOIN SNOW_DIM_CATEGORY c
    ON sc.CATEGORY_KEY = c.CATEGORY_KEY

GROUP BY
    r.REGION_NAME,
    c.CATEGORY_NAME

ORDER BY
    r.REGION_NAME,
    c.CATEGORY_NAME;

SELECT
    ds.REGIONAL_MANAGER,
    SUM(f.QUANTITY) AS TOTAL_ITEMS_SOLD,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM STAR_FACT_SALES f
JOIN STAR_DIM_STORE ds
    ON f.STORE_KEY = ds.STORE_KEY
GROUP BY
    ds.REGIONAL_MANAGER
ORDER BY
    ds.REGIONAL_MANAGER;

--Task14 FINAL AUDIT
SELECT
    'Star Schema' AS SCHEMA_TYPE,
    'STAR_DIM_STORE' AS TABLE_NAME,
    COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_STORE

UNION ALL

SELECT
    'Star Schema',
    'STAR_DIM_PRODUCT',
    COUNT(*)
FROM STAR_DIM_PRODUCT

UNION ALL

SELECT
    'Star Schema',
    'STAR_FACT_SALES',
    COUNT(*)
FROM STAR_FACT_SALES

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_REGION',
    COUNT(*)
FROM SNOW_DIM_REGION

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_STORE',
    COUNT(*)
FROM SNOW_DIM_STORE

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_CATEGORY',
    COUNT(*)
FROM SNOW_DIM_CATEGORY

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_SUBCATEGORY',
    COUNT(*)
FROM SNOW_DIM_SUBCATEGORY

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_PRODUCT',
    COUNT(*)
FROM SNOW_DIM_PRODUCT

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_FACT_SALES',
    COUNT(*)
FROM SNOW_FACT_SALES;