CREATE OR REPLACE WAREHOUSE CUSTOMER_HISTORY_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
create or replace database CUSTOMER_PROFILE3_DB;
CREATE OR REPLACE SCHEMA CUSTOMER_PROFILE3_DB.SCD_SCHEMA;
USE DATABASE CUSTOMER_PROFILE3_DB;
USE SCHEMA SCD_SCHEMA;
CREATE OR REPLACE STAGE CUSTOMER_STAGE;
show stages;
list @CUSTOMER_STAGE;
--phase 6
CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIAL
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

CREATE OR REPLACE TABLE STG_CUSTOMER_UPDATES
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50),
    EFFECTIVE_DATE DATE
);

CREATE OR REPLACE FILE FORMAT CUSTOMER_PROFILE3_DB.SCD_SCHEMA.CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER=1
TRIM_SPACE=TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE;
show file formats;

COPY INTO STG_CUSTOMERS_INITIAL
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM
(
    SELECT
        TRY_TO_NUMBER(TRIM($1)),
        TRIM($2),
        TRIM($3),
        TRIM($4),
        TRIM($5),
        TRIM($6)
    FROM @CUSTOMER_STAGE/customer_intial.csv
)
FILE_FORMAT = (
    FORMAT_NAME = 'CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';

SELECT *
FROM STG_CUSTOMERS_INITIAL
ORDER BY CUSTOMER_ID;

COPY INTO STG_CUSTOMER_UPDATES
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE
)
FROM
(
    SELECT
        TRY_TO_NUMBER(TRIM($1)),
        TRIM($2),
        TRIM($3),
        TRIM($4),
        TRIM($5),
        TRIM($6),
        TRY_TO_DATE(TRIM($7), 'YYYY-MM-DD')
    FROM @CUSTOMER_STAGE/customer_updates.csv
    WHERE NULLIF(TRIM($1), '') IS NOT NULL
)
FILE_FORMAT = (
    FORMAT_NAME = 'CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';

SELECT *
FROM STG_CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

---TASK 2 — Create Hybrid Dimension Table

CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,

    CUSTOMER_ID NUMBER NOT NULL,

    CUSTOMER_NAME VARCHAR(100),

    CITY VARCHAR(100),

    PREVIOUS_CITY VARCHAR(100),

    STATE VARCHAR(100),

    CURRENT_MEMBERSHIP VARCHAR(50),

    PREVIOUS_MEMBERSHIP VARCHAR(50),

    HISTORICAL_MEMBERSHIP VARCHAR(50),

    SEGMENT VARCHAR(50),

    EFFECTIVE_DATE DATE,

    EXPIRY_DATE DATE,

    IS_CURRENT BOOLEAN
);

DESC TABLE DIM_CUSTOMER_HYBRID;

--TASK 3 — Load Initial Dimension Data
INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    NULL AS PREVIOUS_CITY,
    STATE,
    MEMBERSHIP AS CURRENT_MEMBERSHIP,
    NULL AS PREVIOUS_MEMBERSHIP,
    MEMBERSHIP AS HISTORICAL_MEMBERSHIP,
    SEGMENT,
    DATE '2026-01-01',
    DATE '9999-12-31',
    TRUE
FROM STG_CUSTOMERS_INITIAL;

--TASK 3 — Validate Initial Load
SELECT COUNT(*) AS TOTAL_RECORDS
FROM DIM_CUSTOMER_HYBRID;

SELECT COUNT(*) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE;

---TASK 4 — Display Initial Dimension State
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID;

--TASK 5 — Apply Hybrid Updates
UPDATE DIM_CUSTOMER_HYBRID d
SET
    EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE;

SELECT
    CUSTOMER_ID,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID;

--STEP 5.2 — Insert New Active Versions
INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    u.CUSTOMER_ID,
    u.CUSTOMER_NAME,
    u.CITY,

    old.CITY AS PREVIOUS_CITY,

    u.STATE,

    u.MEMBERSHIP AS CURRENT_MEMBERSHIP,

    old.CURRENT_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,

    u.MEMBERSHIP AS HISTORICAL_MEMBERSHIP,

    u.SEGMENT,

    u.EFFECTIVE_DATE,

    DATE '9999-12-31',

    TRUE
FROM STG_CUSTOMER_UPDATES u
JOIN DIM_CUSTOMER_HYBRID old
    ON u.CUSTOMER_ID = old.CUSTOMER_ID
WHERE old.IS_CURRENT = FALSE
  AND old.EXPIRY_DATE =
      DATEADD(DAY, -1, u.EFFECTIVE_DATE);

UPDATE DIM_CUSTOMER_HYBRID d
SET
    CURRENT_MEMBERSHIP = u.MEMBERSHIP
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;


UPDATE DIM_CUSTOMER_HYBRID d
SET
    PREVIOUS_MEMBERSHIP = old_membership.PREVIOUS_VALUE
FROM
(
    SELECT
        u.CUSTOMER_ID,
        MIN_BY(
            d.CURRENT_MEMBERSHIP,
            d.EFFECTIVE_DATE
        ) AS PREVIOUS_VALUE
    FROM STG_CUSTOMER_UPDATES u
    JOIN DIM_CUSTOMER_HYBRID d
        ON u.CUSTOMER_ID = d.CUSTOMER_ID
    GROUP BY u.CUSTOMER_ID
) old_membership
WHERE d.CUSTOMER_ID = old_membership.CUSTOMER_ID;


UPDATE DIM_CUSTOMER_HYBRID d
SET
    PREVIOUS_MEMBERSHIP = h.HISTORICAL_MEMBERSHIP
FROM DIM_CUSTOMER_HYBRID h
WHERE d.CUSTOMER_ID = h.CUSTOMER_ID
  AND h.IS_CURRENT = FALSE;

UPDATE DIM_CUSTOMER_HYBRID d
SET
    CITY = u.CITY
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;

UPDATE DIM_CUSTOMER_HYBRID d
SET
    PREVIOUS_CITY = h.PREVIOUS_CITY
FROM DIM_CUSTOMER_HYBRID h
WHERE d.CUSTOMER_ID = h.CUSTOMER_ID
  AND h.IS_CURRENT = TRUE;

-- Global current city
UPDATE DIM_CUSTOMER_HYBRID d
SET
    CITY = u.CITY
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;


-- Global current state
UPDATE DIM_CUSTOMER_HYBRID d
SET
    STATE = u.STATE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;


-- Global current membership
UPDATE DIM_CUSTOMER_HYBRID d
SET
    CURRENT_MEMBERSHIP = u.MEMBERSHIP
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;


-- Previous membership
UPDATE DIM_CUSTOMER_HYBRID d
SET
    PREVIOUS_MEMBERSHIP = h.HISTORICAL_MEMBERSHIP
FROM DIM_CUSTOMER_HYBRID h
WHERE d.CUSTOMER_ID = h.CUSTOMER_ID
  AND h.IS_CURRENT = FALSE;


-- Previous city
UPDATE DIM_CUSTOMER_HYBRID d
SET
    PREVIOUS_CITY = h.CITY
FROM DIM_CUSTOMER_HYBRID h
WHERE d.CUSTOMER_ID = h.CUSTOMER_ID
  AND h.IS_CURRENT = FALSE;

CREATE OR REPLACE TEMPORARY TABLE TMP_CUSTOMER_OLD_VALUES AS
SELECT
    d.CUSTOMER_ID,
    d.CITY AS OLD_CITY,
    d.STATE AS OLD_STATE,
    d.CURRENT_MEMBERSHIP AS OLD_MEMBERSHIP,
    d.SEGMENT AS OLD_SEGMENT
FROM DIM_CUSTOMER_HYBRID d
JOIN STG_CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.IS_CURRENT = TRUE;

SELECT *
FROM TMP_CUSTOMER_OLD_VALUES
ORDER BY CUSTOMER_ID;

UPDATE DIM_CUSTOMER_HYBRID d
SET
    EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE;
  
INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    u.CUSTOMER_ID,
    u.CUSTOMER_NAME,
    u.CITY,
    o.OLD_CITY,
    u.STATE,
    u.MEMBERSHIP,
    o.OLD_MEMBERSHIP,
    u.MEMBERSHIP,
    u.SEGMENT,
    u.EFFECTIVE_DATE,
    DATE '9999-12-31',
    TRUE
FROM STG_CUSTOMER_UPDATES u
JOIN TMP_CUSTOMER_OLD_VALUES o
    ON u.CUSTOMER_ID = o.CUSTOMER_ID;


UPDATE DIM_CUSTOMER_HYBRID d
SET
    CITY = u.CITY
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;

UPDATE DIM_CUSTOMER_HYBRID d
SET
    STATE = u.STATE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;

UPDATE DIM_CUSTOMER_HYBRID d
SET
    CURRENT_MEMBERSHIP = u.MEMBERSHIP
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;

UPDATE DIM_CUSTOMER_HYBRID d
SET
    PREVIOUS_MEMBERSHIP = o.OLD_MEMBERSHIP
FROM TMP_CUSTOMER_OLD_VALUES o
WHERE d.CUSTOMER_ID = o.CUSTOMER_ID;

--TASK 5 — Validate Updates
SELECT
    CUSTOMER_ID,
    COUNT(*) AS RECORD_COUNT
FROM DIM_CUSTOMER_HYBRID
GROUP BY CUSTOMER_ID
ORDER BY CUSTOMER_ID;

--TASK 6 — Display Complete Dimension History
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY
    CUSTOMER_ID,
    EFFECTIVE_DATE;

--TASK 7 — Display Active Customer Report
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

--TASK 8 — Point-in-Time Historical Query
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101
  AND DATE '2026-03-15'
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;
--TASK 9 — Metric Validation and Record Counts
SELECT
    'TOTAL RECORD COUNT' AS METRIC,
    COUNT(*) AS VALUE
FROM DIM_CUSTOMER_HYBRID

UNION ALL

SELECT
    'CURRENT RECORD COUNT',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT
    'HISTORICAL RECORD COUNT',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = FALSE;

--PHASE 10 — Data Quality Validation
SELECT
    CUSTOMER_ID,
    COUNT(*) AS CURRENT_COUNT
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE
GROUP BY CUSTOMER_ID
HAVING COUNT(*) <> 1;

SELECT *
FROM DIM_CUSTOMER_HYBRID
WHERE EFFECTIVE_DATE > EXPIRY_DATE;

SELECT *
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE
  AND EXPIRY_DATE <> DATE '9999-12-31';

SELECT *
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = FALSE
  AND EXPIRY_DATE = DATE '9999-12-31';
  
--PHASE 11 — Verify Each SCD Strategy
SELECT
    CUSTOMER_ID,
    STATE
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101 limit 2;

SELECT
    CUSTOMER_ID,
    CITY,
    PREVIOUS_CITY
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101 limit 2;

SELECT
    CUSTOMER_ID,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE limit 2;

SELECT
    CUSTOMER_ID,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE limit 2;