CREATE OR REPLACE WAREHOUSE CUSTOMER_HISTORY_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
create or replace database CUSTOMER_PROFILE2_DB;
CREATE OR REPLACE SCHEMA CUSTOMER_PROFILE2_DB.SCD_SCHEMA;
USE DATABASE CUSTOMER_PROFILE2_DB;
USE SCHEMA SCD_SCHEMA;
CREATE OR REPLACE STAGE CUSTOMER_STAGE;
show stages;
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER=1
TRIM_SPACE=TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE;
show FILE FORMATS;
LIST @CUSTOMER_STAGE;


-- stahing tables.
CREATE OR REPLACE TABLE CUSTOMER_PROFILE2_DB.SCD_SCHEMA.STG_CUSTOMERS_INITIAL
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

CREATE OR REPLACE TABLE CUSTOMER_PROFILE2_DB.SCD_SCHEMA.STG_CUSTOMER_UPDATES
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50),
    EFFECTIVE_DATE DATE
);
COPY INTO CUSTOMER_PROFILE2_DB.SCD_SCHEMA.STG_CUSTOMERS_INITIAL
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_PROFILE2_DB.SCD_SCHEMA.CUSTOMER_STAGE/customer_intial.csv
FILE_FORMAT = (
    FORMAT_NAME = 'CUSTOMER_PROFILE2_DB.SCD_SCHEMA.CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';

SELECT *
FROM STG_CUSTOMERS_INITIAL
ORDER BY CUSTOMER_ID;

TRUNCATE TABLE CUSTOMER_PROFILE2_DB.SCD_SCHEMA.STG_CUSTOMER_UPDATES;

COPY INTO CUSTOMER_PROFILE2_DB.SCD_SCHEMA.STG_CUSTOMER_UPDATES
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE
)
FROM @CUSTOMER_PROFILE2_DB.SCD_SCHEMA.CUSTOMER_STAGE/customer_updates.csv
FILE_FORMAT = (
    FORMAT_NAME = 'CUSTOMER_PROFILE2_DB.SCD_SCHEMA.CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';

SELECT *
FROM CUSTOMER_PROFILE2_DB.SCD_SCHEMA.STG_CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

--PHASE 9 — Create SCD Type 3 Dimension
--TASK 2 — Create Type 3 Dimension
CREATE OR REPLACE SEQUENCE CUSTOMER_SCD3_SEQ
START = 1
INCREMENT = 1;

CREATE OR REPLACE TABLE DIM_CUSTOMER_SCD3
(
    CUSTOMER_KEY NUMBER,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    CURRENT_MEMBERSHIP VARCHAR(50),
    PREVIOUS_MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

INSERT OVERWRITE INTO DIM_CUSTOMER_SCD3
(
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
)
SELECT
    ROW_NUMBER() OVER (ORDER BY CUSTOMER_ID) AS CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    CAST(NULL AS VARCHAR(50)),
    SEGMENT
FROM CUSTOMER_PROFILE2_DB.SCD_SCHEMA.STG_CUSTOMERS_INITIAL;

--TASK 4 — Display Initial Type 3 Data
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_SCD3
ORDER BY CUSTOMER_ID;

--TASK 5 and  6 — Apply SCD Type 3 Changes
MERGE INTO CUSTOMER_PROFILE2_DB.SCD_SCHEMA.DIM_CUSTOMER_SCD3 d
USING (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_NAME,
        CITY,
        STATE,
        MEMBERSHIP,
        SEGMENT,
        EFFECTIVE_DATE
    FROM CUSTOMER_PROFILE2_DB.SCD_SCHEMA.STG_CUSTOMER_UPDATES
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CUSTOMER_ID
        ORDER BY EFFECTIVE_DATE DESC, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT
    ) = 1
) u
ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHEN MATCHED AND NVL(d.CURRENT_MEMBERSHIP, '') <> NVL(u.MEMBERSHIP, '') THEN
    UPDATE SET
        PREVIOUS_MEMBERSHIP = d.CURRENT_MEMBERSHIP,
        CURRENT_MEMBERSHIP = u.MEMBERSHIP,
        CITY = u.CITY,
        STATE = u.STATE,
        CUSTOMER_NAME = u.CUSTOMER_NAME,
        SEGMENT = u.SEGMENT;


---TASK 7 — Type 3 Final Report
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_SCD3
ORDER BY CUSTOMER_ID;

--TASK 8 — Demonstrate Type 3
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_SCD3
WHERE CUSTOMER_ID = 101;

--PHASE 10 — SCD TYPE 6
--TASK 9 — Create Type 6 Dimension

CREATE OR REPLACE SEQUENCE CUSTOMER_SCD6_SEQ
START = 1
INCREMENT = 1;


CREATE OR REPLACE TABLE DIM_CUSTOMER_SCD6
(
    CUSTOMER_KEY NUMBER,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    CURRENT_MEMBERSHIP VARCHAR(50),
    PREVIOUS_MEMBERSHIP VARCHAR(50),
    HISTORICAL_MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);


INSERT INTO DIM_CUSTOMER_SCD6
(
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_SCD6_SEQ.NEXTVAL,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    NULL,
    MEMBERSHIP,
    SEGMENT,
    DATE '2026-01-01',
    DATE '9999-12-31',
    TRUE
FROM STG_CUSTOMERS_INITIAL;


--TASK 10 — Validate Initial Type 6 Load
SELECT COUNT(*) AS TOTAL_RECORDS
FROM DIM_CUSTOMER_SCD6;

SELECT COUNT(*) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = TRUE;

---Display Initial Type 6
SELECT *
FROM DIM_CUSTOMER_SCD6
ORDER BY CUSTOMER_ID;


--PHASE 11 — Apply Type 6 Change
--TASK 11 — Customer 101
--Step 1 — Close the Existing Record
UPDATE DIM_CUSTOMER_SCD6 d
SET
    EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE
  AND u.CUSTOMER_ID = 101;
SELECT *
FROM DIM_CUSTOMER_SCD6
WHERE CUSTOMER_ID = 101;  

INSERT INTO DIM_CUSTOMER_SCD6
(
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_SCD6_SEQ.NEXTVAL,
    u.CUSTOMER_ID,
    u.CUSTOMER_NAME,
    u.CITY,
    u.STATE,
    u.MEMBERSHIP,
    old.CURRENT_MEMBERSHIP,
    u.MEMBERSHIP,
    u.SEGMENT,
    u.EFFECTIVE_DATE,
    DATE '9999-12-31',
    TRUE
FROM STG_CUSTOMER_UPDATES u
JOIN DIM_CUSTOMER_SCD6 old
    ON u.CUSTOMER_ID = old.CUSTOMER_ID
WHERE u.CUSTOMER_ID = 101
  AND old.IS_CURRENT = FALSE
  AND old.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE);

--TASK 12 — Apply Remaining Type 6 Changes
BEGIN;

UPDATE DIM_CUSTOMER_SCD6 d
SET
    EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE
  AND u.CUSTOMER_ID IN (103, 104);

INSERT INTO DIM_CUSTOMER_SCD6
(
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_SCD6_SEQ.NEXTVAL,
    u.CUSTOMER_ID,
    u.CUSTOMER_NAME,
    u.CITY,
    u.STATE,
    u.MEMBERSHIP,
    old.CURRENT_MEMBERSHIP,
    u.MEMBERSHIP,
    u.SEGMENT,
    u.EFFECTIVE_DATE,
    DATE '9999-12-31',
    TRUE
FROM STG_CUSTOMER_UPDATES u
JOIN DIM_CUSTOMER_SCD6 old
    ON u.CUSTOMER_ID = old.CUSTOMER_ID
WHERE u.CUSTOMER_ID IN (103, 104)
  AND old.IS_CURRENT = FALSE
  AND old.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE);

COMMIT;

--TASK 13 — Display Complete Type 6 History
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_SCD6
ORDER BY
    CUSTOMER_ID,
    EFFECTIVE_DATE;

--TASK 14 — Current Customer Report
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

--TASK 15 — Point-in-Time Historical Query
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_SCD6
WHERE CUSTOMER_ID = 101
  AND DATE '2026-03-15'
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

--TASK 17 — Record Count Validation
SELECT
    'SCD TYPE 3 RECORD COUNT' AS METRIC,
    COUNT(*) AS RECORD_COUNT
FROM DIM_CUSTOMER_SCD3

UNION ALL

SELECT
    'SCD TYPE 6 RECORD COUNT',
    COUNT(*)
FROM DIM_CUSTOMER_SCD6

UNION ALL

SELECT
    'SCD TYPE 6 CURRENT RECORD COUNT',
    COUNT(*)
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT
    'SCD TYPE 6 HISTORICAL RECORD COUNT',
    COUNT(*)
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = FALSE;

--PHASE 12 — Stronger Validation
SELECT
    CUSTOMER_ID,
    COUNT(*) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = TRUE
GROUP BY CUSTOMER_ID
HAVING COUNT(*) <> 1;

--Validate Historical Records
SELECT
    CUSTOMER_ID,
    COUNT(*) AS HISTORICAL_RECORDS
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = FALSE
GROUP BY CUSTOMER_ID
ORDER BY CUSTOMER_ID;

--Validate Date Ranges
SELECT *
FROM DIM_CUSTOMER_SCD6
WHERE EFFECTIVE_DATE > EXPIRY_DATE;

SELECT *
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = TRUE
  AND EXPIRY_DATE <> DATE '9999-12-31';

SELECT *
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = FALSE
  AND EXPIRY_DATE = DATE '9999-12-31';

--PHASE 13 — Useful Business Queries
-- 1. Current Gold Customers
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = TRUE
  AND CURRENT_MEMBERSHIP = 'Gold'
ORDER BY CUSTOMER_ID;

--2. Customers Whose Membership Changed
SELECT DISTINCT
    CUSTOMER_ID,
    CUSTOMER_NAME
FROM DIM_CUSTOMER_SCD6
WHERE PREVIOUS_MEMBERSHIP IS NOT NULL
ORDER BY CUSTOMER_ID;

--3. Customers with Membership Upgrades
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    PREVIOUS_MEMBERSHIP,
    CURRENT_MEMBERSHIP
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = TRUE
  AND PREVIOUS_MEMBERSHIP IS NOT NULL
ORDER BY CUSTOMER_ID;

--4. Historical Membership of Customer 101
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_SCD6
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

--PHASE 14 — Complete Final Project Validation
SELECT
    'TYPE 3 TOTAL RECORDS' AS METRIC,
    COUNT(*) AS VALUE
FROM DIM_CUSTOMER_SCD3

UNION ALL

SELECT
    'TYPE 6 TOTAL RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_SCD6

UNION ALL

SELECT
    'TYPE 6 CURRENT RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT
    'TYPE 6 HISTORICAL RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = FALSE;

