CREATE OR REPLACE WAREHOUSE ECOMMERCE_19A_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

create or replace database ECOMMERCE_19A_DB
use database  ECOMMERCE_19A_DB

create  or replace schema ECOMMERCE_SCHEMA;
use schema ECOMMERCE_SCHEMA;


-- 2. RAW ORDERS


CREATE OR REPLACE TABLE RAW_ORDERS (
    ORDER_ID VARCHAR,
    ORDER_DATE DATE,
    USER_ID VARCHAR,
    STORE_ID VARCHAR,
    AMOUNT NUMBER(12,2),
    TAX NUMBER(12,2),
    PAYMENT_METHOD VARCHAR,
    SHIPPING_OPTION VARCHAR,
    GIFT_WRAP_FLAG VARCHAR(1)
);

INSERT INTO RAW_ORDERS
VALUES
('ORD-101', '2026-08-20', 'U-401', 'STR-10', 120.00, 10.00, 'Credit',     'Express',  'Y'),
('ORD-102', '2026-08-20', 'U-402', 'STR-10', 250.00, 20.00, 'UPI',        'Standard', 'N'),
('ORD-103', '2026-08-21', 'U-403', 'STR-11',  75.00,  5.00, 'Credit',     'Express',  'N'),
('ORD-104', '2026-08-21', 'U-404', 'STR-11', 410.00, 30.00, 'NetBanking', 'Standard', 'Y'),
('ORD-105', '2026-08-22', 'U-401', 'STR-10', 190.00, 15.00, 'UPI',        'Express',  'Y'),
('ORD-106', '2026-08-22', 'U-405', 'STR-12', 310.00, 25.00, 'Credit',     'Standard', 'N');


-- 3. RAW INVENTORY

CREATE OR REPLACE TABLE RAW_INVENTORY (
    SNAPSHOT_DATE DATE,
    STORE_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    QTY_ON_HAND NUMBER,
    UNIT_COST NUMBER(12,2)
);

INSERT INTO RAW_INVENTORY
VALUES
('2026-08-24', 'STR-10', 'PRD-50', 150, 25.00),
('2026-08-24', 'STR-10', 'PRD-51',   0, 40.00),
('2026-08-24', 'STR-11', 'PRD-50',  80, 25.00),
('2026-08-24', 'STR-11', 'PRD-52', 200, 12.50),
('2026-08-25', 'STR-10', 'PRD-50', 130, 25.00),
('2026-08-25', 'STR-10', 'PRD-51',  50, 40.00);



-- 4. RAW FULFILLMENT


CREATE OR REPLACE TABLE RAW_FULFILLMENT (
    ORDER_ID VARCHAR,
    ORDER_DATE DATE,
    PICK_DATE DATE,
    SHIP_DATE DATE,
    DELIVERY_DATE DATE
);

INSERT INTO RAW_FULFILLMENT
VALUES
('ORD-101', '2026-08-20', '2026-08-21', '2026-08-21', '2026-08-23'),
('ORD-102', '2026-08-20', '2026-08-20', '2026-08-22', '2026-08-24'),
('ORD-103', '2026-08-21', '2026-08-21', '2026-08-22', '2026-08-25'),
('ORD-104', '2026-08-21', '2026-08-22', NULL,         NULL),
('ORD-105', '2026-08-22', '2026-08-22', '2026-08-23', NULL),
('ORD-106', '2026-08-22', '2026-08-23', '2026-08-24', '2026-08-26');

-- TASK 1
-- JUNK DIMENSION

CREATE OR REPLACE TABLE DIM_ORDER_INDICATORS AS
SELECT
    ROW_NUMBER() OVER (
        ORDER BY FIRST_ORDER_ID
    ) AS INDICATOR_SK,

    PAYMENT_METHOD,
    SHIPPING_OPTION,
    GIFT_WRAP_FLAG

FROM (
    SELECT
        PAYMENT_METHOD,
        SHIPPING_OPTION,
        GIFT_WRAP_FLAG,
        MIN(ORDER_ID) AS FIRST_ORDER_ID

    FROM RAW_ORDERS

    GROUP BY
        PAYMENT_METHOD,
        SHIPPING_OPTION,
        GIFT_WRAP_FLAG
);


-- Validate Task 1

SELECT *
FROM DIM_ORDER_INDICATORS
ORDER BY INDICATOR_SK;



-- TASK 2
-- TRANSACTION FACT + DEGENERATE DIMENSION


CREATE OR REPLACE TABLE FACT_SALES_TRANSACTIONS (
    ORDER_ID VARCHAR,
    ORDER_DATE DATE,
    USER_ID VARCHAR,
    STORE_ID VARCHAR,
    INDICATOR_SK NUMBER,
    AMOUNT NUMBER(12,2),
    TAX NUMBER(12,2)
);


INSERT INTO FACT_SALES_TRANSACTIONS
SELECT
    o.ORDER_ID,
    o.ORDER_DATE,
    o.USER_ID,
    o.STORE_ID,
    d.INDICATOR_SK,
    o.AMOUNT,
    o.TAX

FROM RAW_ORDERS o

JOIN DIM_ORDER_INDICATORS d
    ON o.PAYMENT_METHOD = d.PAYMENT_METHOD
   AND o.SHIPPING_OPTION = d.SHIPPING_OPTION
   AND o.GIFT_WRAP_FLAG = d.GIFT_WRAP_FLAG;


-- Validate Task 2

SELECT
    ORDER_ID,
    INDICATOR_SK,
    AMOUNT
FROM FACT_SALES_TRANSACTIONS
ORDER BY ORDER_ID;


-- TASK 3
-- PERIODIC SNAPSHOT FACT


CREATE OR REPLACE TABLE FACT_INVENTORY_SNAPSHOT (
    SNAPSHOT_DATE DATE,
    STORE_ID VARCHAR,
    TOTAL_UNITS_HELD NUMBER,
    TOTAL_INVENTORY_VAL NUMBER(18,2)
);


INSERT INTO FACT_INVENTORY_SNAPSHOT
SELECT
    SNAPSHOT_DATE,
    STORE_ID,

    SUM(QTY_ON_HAND) AS TOTAL_UNITS_HELD,

    SUM(
        QTY_ON_HAND * UNIT_COST
    ) AS TOTAL_INVENTORY_VAL

FROM RAW_INVENTORY

GROUP BY
    SNAPSHOT_DATE,
    STORE_ID;


-- Validate Task 3

SELECT *
FROM FACT_INVENTORY_SNAPSHOT
ORDER BY SNAPSHOT_DATE, STORE_ID;



-- TASK 4
-- ACCUMULATING SNAPSHOT FACT


CREATE OR REPLACE TABLE FACT_ORDER_FULFILLMENT (
    ORDER_ID VARCHAR,
    ORDER_DATE DATE,
    PICK_DATE DATE,
    SHIP_DATE DATE,
    DELIVERY_DATE DATE,
    PICK_LAG_DAYS NUMBER,
    SHIP_LAG_DAYS NUMBER,
    DELIVERY_LAG_DAYS NUMBER,
    TOTAL_FULFILLMENT_DAYS NUMBER
);


INSERT INTO FACT_ORDER_FULFILLMENT
SELECT
    ORDER_ID,
    ORDER_DATE,
    PICK_DATE,
    SHIP_DATE,
    DELIVERY_DATE,

    DATEDIFF(
        DAY,
        ORDER_DATE,
        PICK_DATE
    ) AS PICK_LAG_DAYS,

    DATEDIFF(
        DAY,
        PICK_DATE,
        SHIP_DATE
    ) AS SHIP_LAG_DAYS,

    DATEDIFF(
        DAY,
        SHIP_DATE,
        DELIVERY_DATE
    ) AS DELIVERY_LAG_DAYS,

    DATEDIFF(
        DAY,
        ORDER_DATE,
        DELIVERY_DATE
    ) AS TOTAL_FULFILLMENT_DAYS

FROM RAW_FULFILLMENT;


-- Validate Task 4

SELECT
    ORDER_ID,
    PICK_LAG_DAYS,
    SHIP_LAG_DAYS,
    DELIVERY_LAG_DAYS,
    TOTAL_FULFILLMENT_DAYS

FROM FACT_ORDER_FULFILLMENT

WHERE DELIVERY_LAG_DAYS IS NOT NULL

ORDER BY ORDER_ID;



-- TASK 5
-- INCOMPLETE LIFECYCLE STATUS


SELECT
    ORDER_ID,
    ORDER_DATE,

    CASE
        WHEN DELIVERY_DATE IS NOT NULL
            THEN 'DELIVERED'

        WHEN SHIP_DATE IS NOT NULL
            THEN 'SHIPPED_NOT_DELIVERED'

        WHEN PICK_DATE IS NOT NULL
            THEN 'PICKED_NOT_SHIPPED'

        ELSE 'ORDERED_NOT_PICKED'
    END AS CURRENT_STATUS

FROM FACT_ORDER_FULFILLMENT

WHERE DELIVERY_DATE IS NULL

ORDER BY ORDER_ID;



-- TASK 6
-- REVENUE BY JUNK DIMENSION


SELECT
    d.PAYMENT_METHOD,

    COUNT(f.ORDER_ID) AS TOTAL_ORDERS,

    SUM(f.AMOUNT) AS TOTAL_REVENUE

FROM FACT_SALES_TRANSACTIONS f

JOIN DIM_ORDER_INDICATORS d
    ON f.INDICATOR_SK = d.INDICATOR_SK

GROUP BY
    d.PAYMENT_METHOD

ORDER BY
    d.PAYMENT_METHOD;