CREATE OR REPLACE WAREHOUSE LOGISTICS_LAKEHOUSE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE LOGISTICS_LAKEHOUSE_DB;

USE DATABASE LOGISTICS_LAKEHOUSE_DB;

CREATE OR REPLACE SCHEMA FLEET_CORE;

USE SCHEMA FLEET_CORE;

--- creting the breone table
CREATE OR REPLACE TABLE BRONZE_IOT_STREAMS
(
    INGEST_ID NUMBER AUTOINCREMENT,
    RAW_PAYLOAD VARIANT,
    RECORDED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

--- CREATING THE STAGING TABLE TO STORE THE RAW DATA INTO INTO IT
CREATE OR REPLACE TEMPORARY TABLE RAW_IOT_INGEST
(
    RAW_RECORD_TEXT VARCHAR
);

--- INGESTION OF JSON DATA OF BATCH 1,2,3 ...
INSERT INTO RAW_IOT_INGEST (RAW_RECORD_TEXT)
VALUES
('{"payload_id":"PL-801","payload_type":"TELEMATICS","timestamp":"2026-08-01T06:00:00Z","data":{"trip_id":"TRP-101","vehicle_id":"TRK-9001","driver_name":"John Doe","distance_km":450.0,"fuel_consumed_liters":120.0,"speed_avg":75.0}}'),

('{"payload_id":"PL-802","payload_type":"CUSTOMS","timestamp":"2026-08-01T06:30:00Z","data":{"shipment_id":"SHP-5001","vehicle_id":"TRK-9001","destination_country":"CAN","declared_value":85000.00,"duty_pct":5.0,"clearance_status":"CLEARED"}}'),

('{"payload_id":"PL-803","payload_type":"TELEMATICS","timestamp":"2026-08-01T07:00:00Z","data":{"trip_id":"TRP-102","vehicle_id":"TRK-9002","driver_name":"Jane Smith","distance_km":620.0,"fuel_consumed_liters":180.0,"speed_avg":82.0}}'),

('{"payload_id":"PL-804","payload_type":"CUSTOMS","timestamp":"2026-08-01T07:45:00Z","data":{"shipment_id":"SHP-5002","vehicle_id":"TRK-9002","destination_country":"MEX","declared_value":42000.00,"duty_pct":7.5,"clearance_status":"CLEARED"}}');

INSERT INTO RAW_IOT_INGEST (RAW_RECORD_TEXT)
VALUES
('{"payload_id":"PL-805","payload_type":"TELEMATICS","timestamp":"2026-08-01T08:15:00Z","data":{"trip_id":"TRP-103","vehicle_id":"TRK-9003","driver_name":"Robert Brown","distance_km":310.0,"fuel_consumed_liters":95.0,"speed_avg":68.0,"driver_fatigue_score":1.2}}'),

('{"payload_id":"PL-806","payload_type":"CUSTOMS","timestamp":"2026-08-01T08:30:00Z","data":{"shipment_id":"SHP-5003","vehicle_id":"TRK-9003","destination_country":"CAN","declared_value":120000.00,"duty_pct":4.0,"clearance_status":"CLEARED","border_clearance_code":"FAST_PASS_01"}'),

('{"payload_id":"PL-807","payload_type":"CUSTOMS","timestamp":"2026-08-01T09:00:00Z","data":{"shipment_id":"SHP-5004","vehicle_id":"TRK-9001","destination_country":"MEX","declared_value":15000.00,"duty_pct":7.5,"clearance_status":"HELD_INSPECTION","border_clearance_code":null}}');


INSERT INTO RAW_IOT_INGEST (RAW_RECORD_TEXT)
VALUES
('{"payload_id":"PL-808","payload_type":"TELEMATICS","timestamp":"2026-08-01T09:30:00Z","data":{"trip_id":"TRP-104","vehicle_id":"TRK-9004","driver_name":"Alice Green","distance_km":0.0,"fuel_consumed_liters":0.0,"speed_avg":0.0,"driver_fatigue_score":0.0}}'),

('{"MALFORMED_IOT_SENSOR_BINARY_BURST_DATA_ERR"}');

USE DATABASE LOGISTICS_LAKEHOUSE_DB;
USE SCHEMA FLEET_CORE;

TRUNCATE TABLE BRONZE_IOT_STREAMS;

TRUNCATE TABLE RAW_IOT_INGEST;


INSERT INTO BRONZE_IOT_STREAMS
(
    RAW_PAYLOAD,
    RECORDED_AT
)
SELECT
    TRY_PARSE_JSON(RAW_RECORD_TEXT),
    CURRENT_TIMESTAMP()
FROM RAW_IOT_INGEST
WHERE TRY_PARSE_JSON(RAW_RECORD_TEXT) IS NOT NULL;

-- VERIFY THE DATA 
SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS
FROM BRONZE_IOT_STREAMS;

--
SELECT 
    RAW_PAYLOAD:payload_id::VARCHAR AS PAYLOAD_ID,
    RAW_PAYLOAD:payload_type::VARCHAR AS PAYLOAD_TYPE,
    RAW_PAYLOAD:timestamp::TIMESTAMP_TZ AS EVENT_TIMESTAMP,

    RAW_PAYLOAD:data:trip_id::VARCHAR AS TRIP_ID,

    RAW_PAYLOAD:data:vehicle_id::VARCHAR AS VEHICLE_ID,

    RAW_PAYLOAD:data:shipment_id::VARCHAR AS SHIPMENT_ID,

    RAW_PAYLOAD:data:destination_country::VARCHAR AS DESTINATION_COUNTRY,

    RAW_PAYLOAD:data:declared_value::NUMBER(18,2) AS DECLARED_VALUE

FROM BRONZE_IOT_STREAMS
ORDER BY EVENT_TIMESTAMP;

--Create quarantine table
CREATE OR REPLACE TABLE QUARANTINE_IOT_PAYLOADS
(
    QUARANTINE_ID NUMBER AUTOINCREMENT,
    RAW_RECORD_TEXT VARCHAR,
    REASON VARCHAR
);


-- Insert malformed records


INSERT INTO QUARANTINE_IOT_PAYLOADS
(
    RAW_RECORD_TEXT,
    REASON
)
SELECT
    RAW_RECORD_TEXT,
    'MALFORMED_JSON_BODY'
FROM RAW_IOT_INGEST
WHERE TRY_PARSE_JSON(RAW_RECORD_TEXT) IS NULL;
--- Verify quarantine
SELECT
    QUARANTINE_ID,
    RAW_RECORD_TEXT,
    REASON
FROM QUARANTINE_IOT_PAYLOADS;


--TASK 3 — Silver Layer



---Create Silver table


CREATE OR REPLACE TABLE SILVER_CUSTOMS_CLEARANCE
(
    SHIPMENT_ID VARCHAR(50),
    PAYLOAD_ID VARCHAR(50),
    VEHICLE_ID VARCHAR(50),
    DESTINATION_COUNTRY VARCHAR(10),
    DECLARED_VALUE NUMBER(18,2),
    DUTY_PCT NUMBER(8,2),
    DUTY_AMOUNT_DUE NUMBER(18,2),
    BORDER_CODE VARCHAR(100),
    CLEARANCE_STATUS VARCHAR(50)
);

-- Transform Bronze → Silver


INSERT INTO SILVER_CUSTOMS_CLEARANCE
(
    SHIPMENT_ID,
    PAYLOAD_ID,
    VEHICLE_ID,
    DESTINATION_COUNTRY,
    DECLARED_VALUE,
    DUTY_PCT,
    DUTY_AMOUNT_DUE,
    BORDER_CODE,
    CLEARANCE_STATUS
)
SELECT
    RAW_PAYLOAD:data:shipment_id::VARCHAR AS SHIPMENT_ID,

    RAW_PAYLOAD:payload_id::VARCHAR AS PAYLOAD_ID,

    RAW_PAYLOAD:data:vehicle_id::VARCHAR AS VEHICLE_ID,

    RAW_PAYLOAD:data:destination_country::VARCHAR AS DESTINATION_COUNTRY,

    RAW_PAYLOAD:data:declared_value::NUMBER(18,2) AS DECLARED_VALUE,

    RAW_PAYLOAD:data:duty_pct::NUMBER(8,2) AS DUTY_PCT,

    ROUND(
        RAW_PAYLOAD:data:declared_value::NUMBER(18,2)
        *
        (
            RAW_PAYLOAD:data:duty_pct::NUMBER(8,2) / 100
        ),
        2
    ) AS DUTY_AMOUNT_DUE,

    RAW_PAYLOAD:data:border_clearance_code::VARCHAR AS BORDER_CODE,

    RAW_PAYLOAD:data:clearance_status::VARCHAR AS CLEARANCE_STATUS

FROM BRONZE_IOT_STREAMS
WHERE RAW_PAYLOAD:payload_type::VARCHAR = 'CUSTOMS';

-- Verify Silver

SELECT
    SHIPMENT_ID,
    VEHICLE_ID,
    DESTINATION_COUNTRY,
    DECLARED_VALUE,
    DUTY_PCT,
    DUTY_AMOUNT_DUE,
    BORDER_CODE,
    CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
ORDER BY SHIPMENT_ID;

SELECT
    COUNT(*) AS TOTAL_CUSTOMS_RECORDS,

    COUNT_IF(SHIPMENT_ID IS NULL) AS NULL_SHIPMENT_IDS,

    COUNT_IF(DECLARED_VALUE IS NULL) AS NULL_DECLARED_VALUES,

    COUNT_IF(DUTY_PCT IS NULL) AS NULL_DUTY_RATES,

    COUNT_IF(DUTY_AMOUNT_DUE IS NULL) AS NULL_DUTY_AMOUNTS

FROM SILVER_CUSTOMS_CLEARANCE


--TASK 4  Gold Strategic Aggregation

CREATE OR REPLACE TABLE GOLD_COUNTRY_DUTY_SUMMARY
(
    DEST_COUNTRY VARCHAR(10),
    TOTAL_CLEARED_VAL NUMBER(18,2),
    TOTAL_DUTIES_COLLECTED NUMBER(18,2),
    AVG_DUTY_RATE_PCT NUMBER(8,2),
    CLEARED_SHIPMENTS NUMBER
);

--Populate Gold


INSERT INTO GOLD_COUNTRY_DUTY_SUMMARY
(
    DEST_COUNTRY,
    TOTAL_CLEARED_VAL,
    TOTAL_DUTIES_COLLECTED,
    AVG_DUTY_RATE_PCT,
    CLEARED_SHIPMENTS
)
SELECT
    DESTINATION_COUNTRY AS DEST_COUNTRY,

    SUM(DECLARED_VALUE) AS TOTAL_CLEARED_VAL,

    SUM(DUTY_AMOUNT_DUE) AS TOTAL_DUTIES_COLLECTED,

    ROUND(AVG(DUTY_PCT), 2) AS AVG_DUTY_RATE_PCT,

    COUNT(*) AS CLEARED_SHIPMENTS

FROM SILVER_CUSTOMS_CLEARANCE
WHERE CLEARANCE_STATUS = 'CLEARED'

GROUP BY DESTINATION_COUNTRY;

-- Verify Gold


SELECT *
FROM GOLD_COUNTRY_DUTY_SUMMARY
ORDER BY DEST_COUNTRY;


TRUNCATE TABLE GOLD_COUNTRY_DUTY_SUMMARY;

INSERT INTO GOLD_COUNTRY_DUTY_SUMMARY
(
    DEST_COUNTRY,
    TOTAL_CLEARED_VAL,
    TOTAL_DUTIES_COLLECTED,
    AVG_DUTY_RATE_PCT,
    CLEARED_SHIPMENTS
)
SELECT
    DESTINATION_COUNTRY,

    SUM(DECLARED_VALUE),

    SUM(DUTY_AMOUNT_DUE),

    ROUND(
        SUM(DUTY_AMOUNT_DUE)
        / NULLIF(SUM(DECLARED_VALUE), 0)
        * 100,
        2
    ),

    COUNT(*)

FROM SILVER_CUSTOMS_CLEARANCE
WHERE CLEARANCE_STATUS = 'CLEARED'

GROUP BY DESTINATION_COUNTRY;


---TASK 5 — Disaster Recovery Using Time Travel
 --First create a safety checkpoint  BEFORE WE ARE COUURPTING THE DATA AFTEER DTA DATA DISASTER 
 SELECT
    DESTINATION_COUNTRY,
    CLEARANCE_STATUS,
    COUNT(*) AS RECORD_COUNT
FROM SILVER_CUSTOMS_CLEARANCE
GROUP BY
    DESTINATION_COUNTRY,
    CLEARANCE_STATUS
ORDER BY
    DESTINATION_COUNTRY,
    CLEARANCE_STATUS;

--  SHIPMENT UPDATING TO REJECTING 

UPDATE SILVER_CUSTOMS_CLEARANCE
SET CLEARANCE_STATUS = 'REJECTED'
WHERE DESTINATION_COUNTRY = 'CAN';


SELECT
    SHIPMENT_ID,
    DESTINATION_COUNTRY,
    CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
ORDER BY SHIPMENT_ID;


SELECT
    DESTINATION_COUNTRY,
    CLEARANCE_STATUS,
    COUNT(*) AS RECORD_COUNT
FROM SILVER_CUSTOMS_CLEARANCE
GROUP BY
    DESTINATION_COUNTRY,
    CLEARANCE_STATUS
ORDER BY
    DESTINATION_COUNTRY,
    CLEARANCE_STATUS;

--Time Travel inspect previous state
SELECT
    SHIPMENT_ID,
    DESTINATION_COUNTRY,
    CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
BEFORE (STATEMENT => LAST_QUERY_ID());

UPDATE SILVER_CUSTOMS_CLEARANCE
SET CLEARANCE_STATUS = 'REJECTED'
WHERE DESTINATION_COUNTRY = 'CAN';

SELECT LAST_QUERY_ID();

SELECT *
FROM SILVER_CUSTOMS_CLEARANCE
AT
(
    OFFSET => -60
);


-- BEFORE DAMAGE
SET RECOVERY_POINT = CURRENT_TIMESTAMP();

-- SIMULATE ROGUE UPDATE
UPDATE SILVER_CUSTOMS_CLEARANCE
SET CLEARANCE_STATUS = 'REJECTED'
WHERE DESTINATION_COUNTRY = 'CAN';

-- RECOVER PREVIOUS VERSION
CREATE OR REPLACE TABLE SILVER_CUSTOMS_CLEARANCE_RECOVERY AS
SELECT *
FROM SILVER_CUSTOMS_CLEARANCE
AT
(
    TIMESTAMP => $RECOVERY_POINT
);

-- VERIFY RECOVERED DATA
SELECT *
FROM SILVER_CUSTOMS_CLEARANCE_RECOVERY
ORDER BY SHIPMENT_ID;
SELECT *
FROM SILVER_CUSTOMS_CLEARANCE_RECOVERY
ORDER BY SHIPMENT_ID;

CREATE OR REPLACE TABLE SILVER_CUSTOMS_CLEARANCE
AS
SELECT *
FROM SILVER_CUSTOMS_CLEARANCE_RECOVERY;


SELECT *
FROM SILVER_CUSTOMS_CLEARANCE
ORDER BY SHIPMENT_ID;


--Final recovery audit
SELECT
    DESTINATION_COUNTRY,

    COUNT_IF(CLEARANCE_STATUS = 'CLEARED')
        AS CLEARED_COUNT,

    COUNT_IF(CLEARANCE_STATUS = 'REJECTED')
        AS REJECTED_COUNT

FROM SILVER_CUSTOMS_CLEARANCE

GROUP BY DESTINATION_COUNTRY

ORDER BY DESTINATION_COUNTRY;


--TASK 6 — End-to-End   Reconciliation
SELECT
    SUM(
        RAW_PAYLOAD:data:declared_value::NUMBER(18,2)
    ) AS BRONZE_GROSS_TOTAL
FROM BRONZE_IOT_STREAMS
WHERE RAW_PAYLOAD:payload_type::VARCHAR = 'CUSTOMS';

SELECT
    SUM(DECLARED_VALUE) AS SILVER_GROSS_TOTAL
FROM SILVER_CUSTOMS_CLEARANCE;

SELECT
    SUM(TOTAL_CLEARED_VAL) AS GOLD_GROSS_TOTAL
FROM GOLD_COUNTRY_DUTY_SUMMARY;

--- complete  Reconciliation
WITH BRONZE_TOTAL AS
(
    SELECT
        COALESCE(
            SUM(
                RAW_PAYLOAD:data:declared_value::NUMBER(18,2)
            ),
            0
        ) AS BRONZE_GROSS_TOTAL
    FROM BRONZE_IOT_STREAMS
    WHERE RAW_PAYLOAD:payload_type::VARCHAR = 'CUSTOMS'
),

SILVER_TOTAL AS
(
    SELECT
        COALESCE(SUM(DECLARED_VALUE), 0)
            AS SILVER_GROSS_TOTAL
    FROM SILVER_CUSTOMS_CLEARANCE
),

GOLD_TOTAL AS
(
    SELECT
        COALESCE(SUM(TOTAL_CLEARED_VAL), 0)
            AS GOLD_GROSS_TOTAL
    FROM GOLD_COUNTRY_DUTY_SUMMARY
)

SELECT
    BRONZE_GROSS_TOTAL,
    SILVER_GROSS_TOTAL,
    GOLD_GROSS_TOTAL,

    CASE
        WHEN BRONZE_GROSS_TOTAL = SILVER_GROSS_TOTAL
        THEN TRUE
        ELSE FALSE
    END AS RECONCILED_FLAG

FROM BRONZE_TOTAL
CROSS JOIN SILVER_TOTAL
CROSS JOIN GOLD_TOTAL;


