CREATE OR REPLACE WAREHOUSE CUSTOMER_HISTORY_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

create or replace database CUSTOMER_PROFILE4_DB;
CREATE OR REPLACE SCHEMA CUSTOMER_PROFILE4_DB.SCD_SCHEMA;
USE DATABASE CUSTOMER_PROFILE4_DB;
USE SCHEMA SCD_SCHEMA;
CREATE OR REPLACE STAGE CUSTOMER_STAGE;
show stages;
--TASK 2 — Create DIM_STORE
CREATE OR REPLACE TABLE DIM_STORE
(
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    STORE_MANAGER VARCHAR(100)
);
DESC TABLE DIM_STORE;

--TASK 3 — Create DIM_PRODUCT
CREATE OR REPLACE TABLE DIM_PRODUCT
(
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);
--TASK 4 — Create DIM_CUSTOMER_HYBRID
CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    PREVIOUS_CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);
INSERT INTO DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
)
VALUES
(201, 'Metro Flagship', 'Hyderabad', 'Telangana', 'Rajesh Kumar'),
(202, 'Express Hub', 'Warangal', 'Telangana', 'Sita Sharma'),
(203, 'Coastal Center', 'Vijayawada', 'Andhra Pradesh', 'Vikram Rao');
SELECT *
FROM DIM_STORE
ORDER BY STORE_ID;

INSERT INTO DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
)
VALUES
(501, 'Laptop Pro', 'Electronics', 75000.00),
(502, 'Wireless Mouse', 'Electronics', 1500.00),
(503, 'Ergonomic Chair', 'Furniture', 12000.00),
(504, 'Coffee Maker', 'Appliances', 4500.00);

select * from DIM_PRODUCT order by product_id;

--TASK 6 — Populate Initial Customer Dimension
INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
VALUES
(
    101,
    'Amit Sharma',
    'Hyderabad',
    NULL,
    'Telangana',
    'Silver',
    NULL,
    'Silver',
    'Regular',
    '2026-01-01',
    '9999-12-31',
    TRUE
),
(
    102,
    'Priya Reddy',
    'Warangal',
    NULL,
    'Telangana',
    'Gold',
    NULL,
    'Gold',
    'Premium',
    '2026-01-01',
    '9999-12-31',
    TRUE
),
(
    103,
    'Rahul Verma',
    'Vijayawada',
    NULL,
    'Andhra Pradesh',
    'Silver',
    NULL,
    'Silver',
    'Regular',
    '2026-01-01',
    '9999-12-31',
    TRUE
),
(
    104,
    'Neha Patel',
    'Hyderabad',
    NULL,
    'Telangana',
    'Gold',
    NULL,
    'Gold',
    'Premium',
    '2026-01-01',
    '9999-12-31',
    TRUE
),
(
    105,
    'Arjun Gupta',
    'Nagpur',
    NULL,
    'Maharashtra',
    'Bronze',
    NULL,
    'Bronze',
    'Regular',
    '2026-01-01',
    '9999-12-31',
    TRUE
);
SELECT *
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID;

-- Tak 7 Create FACT_SALES
CREATE OR REPLACE TABLE FACT_SALES
(
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,

    TRANSACTION_ID VARCHAR(50),

    TRANSACTION_DATE DATE,

    CUSTOMER_KEY NUMBER,

    STORE_KEY NUMBER,

    PRODUCT_KEY NUMBER,

    QUANTITY NUMBER,

    UNIT_PRICE NUMBER(10,2),

    TOTAL_AMOUNT NUMBER(12,2),

    FOREIGN KEY (CUSTOMER_KEY)
        REFERENCES DIM_CUSTOMER_HYBRID(CUSTOMER_KEY),

    FOREIGN KEY (STORE_KEY)
        REFERENCES DIM_STORE(STORE_KEY),

    FOREIGN KEY (PRODUCT_KEY)
        REFERENCES DIM_PRODUCT(PRODUCT_KEY)
);
--TASK 8 — Insert Q1 2026 Sales
INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1001',
    '2026-02-15',
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    1,
    p.UNIT_PRICE,
    1 * p.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID c
JOIN DIM_STORE s
    ON s.STORE_ID = 201
JOIN DIM_PRODUCT p
    ON p.PRODUCT_ID = 501
WHERE c.CUSTOMER_ID = 101
  AND c.IS_CURRENT = TRUE;

  INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1002',
    '2026-03-10',
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    2,
    p.UNIT_PRICE,
    2 * p.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID c
JOIN DIM_STORE s
    ON s.STORE_ID = 203
JOIN DIM_PRODUCT p
    ON p.PRODUCT_ID = 502
WHERE c.CUSTOMER_ID = 103
  AND c.IS_CURRENT = TRUE ;
SELECT *
FROM FACT_SALES
ORDER BY  SALES_KEY ;

--TASK 9 — Store Manager SCD Type 1 Update
UPDATE DIM_STORE
SET STORE_MANAGER = 'Suresh Menon'
WHERE STORE_ID = 201;
SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
FROM DIM_STORE
WHERE STORE_ID = 201;

--TASK 10 — Execute Multi-Attribute Customer Updates
UPDATE DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = '2026-03-31',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101
  AND IS_CURRENT = TRUE;

UPDATE DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = '2026-04-04',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = TRUE;

UPDATE DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = '2026-04-09',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    'Bengaluru',
    CITY,
    'Karnataka',
    'Gold',
    CURRENT_MEMBERSHIP,
    'Gold',
    'Premium',
    '2026-04-01',
    '9999-12-31',
    TRUE
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101
  AND EXPIRY_DATE = '2026-03-31';

  INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    'Chennai',
    CITY,
    'Tamil Nadu',
    'Gold',
    CURRENT_MEMBERSHIP,
    'Gold',
    'Premium',
    '2026-04-05',
    '9999-12-31',
    TRUE
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 103
  AND EXPIRY_DATE = '2026-04-04';

INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    'Platinum',
    CURRENT_MEMBERSHIP,
    'Platinum',
    SEGMENT,
    '2026-04-10',
    '9999-12-31',
    TRUE
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 104
  AND EXPIRY_DATE = '2026-04-09';

UPDATE DIM_CUSTOMER_HYBRID
SET
    CITY = 'Bengaluru',
    STATE = 'Karnataka',
    CURRENT_MEMBERSHIP = 'Gold',
    PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 101;

UPDATE DIM_CUSTOMER_HYBRID
SET
    CITY = 'Chennai',
    STATE = 'Tamil Nadu',
    CURRENT_MEMBERSHIP = 'Gold',
    PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER_HYBRID
SET
    CITY = 'Hyderabad',
    STATE = 'Telangana',
    CURRENT_MEMBERSHIP = 'Platinum',
    PREVIOUS_MEMBERSHIP = 'Gold'
WHERE CUSTOMER_ID = 104;

--TASK 11 — Insert Q2 2026 Sales Transaction
INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-2001',
    '2026-04-15',
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    1,
    p.UNIT_PRICE,
    1 * p.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID c
JOIN DIM_STORE s
    ON s.STORE_ID = 201
JOIN DIM_PRODUCT p
    ON p.PRODUCT_ID = 503
WHERE c.CUSTOMER_ID = 101
  AND c.IS_CURRENT = TRUE;

SELECT
    f.TRANSACTION_ID,
    f.TRANSACTION_DATE,
    c.CUSTOMER_ID,
    c.CUSTOMER_KEY,
    c.EFFECTIVE_DATE,
    c.IS_CURRENT,
    p.PRODUCT_NAME,
    f.TOTAL_AMOUNT
FROM FACT_SALES f
JOIN DIM_CUSTOMER_HYBRID c
    ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_PRODUCT p
    ON f.PRODUCT_KEY = p.PRODUCT_KEY
WHERE f.TRANSACTION_ID = 'TXN-2001';

--TASK 12 — Display Full Customer Dimension History
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY
    CUSTOMER_ID,
    EFFECTIVE_DATE;

--TASK 13 — Point-in-Time POS Analytics
SELECT
    f.TRANSACTION_ID,
    f.TRANSACTION_DATE,
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CITY AS CURRENT_CITY,
    c.HISTORICAL_MEMBERSHIP AS MEMBERSHIP_AT_PURCHASE,
    c.SEGMENT AS SEGMENT_AT_PURCHASE,
    s.STORE_NAME,
    p.PRODUCT_NAME,
    f.TOTAL_AMOUNT
FROM FACT_SALES f
JOIN DIM_CUSTOMER_HYBRID c
    ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_STORE s
    ON f.STORE_KEY = s.STORE_KEY
JOIN DIM_PRODUCT p
    ON f.PRODUCT_KEY = p.PRODUCT_KEY
WHERE c.CUSTOMER_ID = 101
ORDER BY f.TRANSACTION_DATE;

--TASK 14 — Warehouse Record Count and Data Auditing
SELECT
    'STORE DIMENSION RECORDS' AS METRIC,
    COUNT(*) AS VALUE
FROM DIM_STORE

UNION ALL

SELECT
    'PRODUCT DIMENSION RECORDS',
    COUNT(*)
FROM DIM_PRODUCT

UNION ALL

SELECT
    'TOTAL CUSTOMER DIMENSION RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID

UNION ALL

SELECT
    'CURRENT CUSTOMER RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT
    'HISTORICAL CUSTOMER RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = FALSE

UNION ALL

SELECT
    'FACT SALES TRANSACTIONS',
    COUNT(*)
FROM FACT_SALES;