CREATE OR REPLACE WAREHOUSE FINANCIAL_GATEWAY_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
    create or replace database FINANCIAL_GATEWAY_DB;
    create or replace schema PAYMENT_ANALYTICS;
    use schema PAYMENT_ANALYTICS;
    
--- WE APPLY MEDALLION ARCHITECTURE (BRONZE)

    CREATE OR REPLACE TABLE BRONZE_PAYMENT_PAYLOADS (
    INGESTION_ID NUMBER AUTOINCREMENT,
    RAW_PAYLOAD VARIANT,
    INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);


DELETE FROM BRONZE_PAYMENT_PAYLOADS;


INSERT INTO BRONZE_PAYMENT_PAYLOADS (RAW_PAYLOAD)
SELECT PARSE_JSON($$
{"txn_id":"TXN-901","txn_time":"2026-07-10T10:00:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":50000.00,"fee_pct":2.5,"status":"APPROVED"}
$$)
UNION ALL
SELECT PARSE_JSON($$
{"txn_id":"TXN-902","txn_time":"2026-07-10T10:15:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":12000.00,"fee_pct":3.0,"status":"APPROVED"}
$$)
UNION ALL
SELECT PARSE_JSON($$
{"txn_id":"TXN-903","txn_time":"2026-07-10T11:00:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":25000.00,"fee_pct":2.5,"status":"PENDING"}
$$)
UNION ALL
SELECT PARSE_JSON($$
{"txn_id":"TXN-904","txn_time":"2026-07-10T11:30:00Z","merchant_id":303,"merchant_name":"FreshMart","card_number":"4000111122223333","amount":8500.00,"fee_pct":1.8,"status":"APPROVED"}
$$)
UNION ALL
SELECT PARSE_JSON($$
{"txn_id":"TXN-905","txn_time":"2026-07-10T12:00:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":45000.00,"fee_pct":3.0,"status":"DECLINED"}
$$)
UNION ALL
SELECT PARSE_JSON($$
{"txn_id":"TXN-906","txn_time":"2026-07-10T12:30:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":150000.00,"fee_pct":2.5,"status":"APPROVED"}
$$)
UNION ALL
SELECT PARSE_JSON($$
{"txn_id":"TXN-907","txn_time":"2026-07-10T13:00:00Z","merchant_id":303,"merchant_name":"FreshMart","card_number":"4000111122223333","amount":3200.00,"fee_pct":1.8,"status":"APPROVED"}
$$)
UNION ALL
SELECT PARSE_JSON($$
{"txn_id":"TXN-908","txn_time":"2026-07-10T13:15:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":67000.00,"fee_pct":3.0,"status":"PENDING"}
$$);

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS_CT
FROM BRONZE_PAYMENT_PAYLOADS;

-- SILVER TABLE 
SELECT
    RAW_PAYLOAD:txn_id::VARCHAR AS TXN_ID,
    RAW_PAYLOAD:merchant_id::NUMBER AS MERCHANT_ID,
    RAW_PAYLOAD:merchant_name::VARCHAR AS MERCHANT_NAME,
    RAW_PAYLOAD:amount::NUMBER(12,2) AS AMOUNT,
    RAW_PAYLOAD:fee_pct::NUMBER(5,2) AS FEE_PCT,
    RAW_PAYLOAD:status::VARCHAR AS STATUS
FROM BRONZE_PAYMENT_PAYLOADS
ORDER BY TXN_ID;

-- SILVER TABLE 
CREATE OR REPLACE TABLE SILVER_CLEANED_TRANSACTIONS (
    TXN_ID VARCHAR,
    TXN_TIME TIMESTAMP_TZ,
    MERCHANT_ID NUMBER,
    MERCHANT_NAME VARCHAR,

    MASKED_CARD VARCHAR,

    GROSS_AMOUNT NUMBER(14,2),
    FEE_PCT NUMBER(5,2),

    PROCESSING_FEE NUMBER(14,2),
    NET_SETTLEMENT_AMOUNT NUMBER(14,2),

    STATUS VARCHAR,

    SILVER_CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO SILVER_CLEANED_TRANSACTIONS (
    TXN_ID,
    TXN_TIME,
    MERCHANT_ID,
    MERCHANT_NAME,
    MASKED_CARD,
    GROSS_AMOUNT,
    FEE_PCT,
    PROCESSING_FEE,
    NET_SETTLEMENT_AMOUNT,
    STATUS
)
SELECT
    RAW_PAYLOAD:txn_id::VARCHAR AS TXN_ID,

    RAW_PAYLOAD:txn_time::TIMESTAMP_TZ AS TXN_TIME,

    RAW_PAYLOAD:merchant_id::NUMBER AS MERCHANT_ID,

    RAW_PAYLOAD:merchant_name::VARCHAR AS MERCHANT_NAME,

    'XXXX-XXXX-XXXX-' ||
    RIGHT(
        RAW_PAYLOAD:card_number::VARCHAR,
        4
    ) AS MASKED_CARD,

    RAW_PAYLOAD:amount::NUMBER(14,2) AS GROSS_AMOUNT,

    RAW_PAYLOAD:fee_pct::NUMBER(5,2) AS FEE_PCT,

    ROUND(
        RAW_PAYLOAD:amount::NUMBER(14,2)
        *
        (
            RAW_PAYLOAD:fee_pct::NUMBER(5,2) / 100
        ),
        2
    ) AS PROCESSING_FEE,

    ROUND(
        RAW_PAYLOAD:amount::NUMBER(14,2)
        -
        (
            RAW_PAYLOAD:amount::NUMBER(14,2)
            *
            (
                RAW_PAYLOAD:fee_pct::NUMBER(5,2) / 100
            )
        ),
        2
    ) AS NET_SETTLEMENT_AMOUNT,

    RAW_PAYLOAD:status::VARCHAR AS STATUS

FROM BRONZE_PAYMENT_PAYLOADS;


SELECT
    TXN_ID,
    MERCHANT_ID,
    MERCHANT_NAME,
    MASKED_CARD,
    GROSS_AMOUNT AS GROSS,
    PROCESSING_FEE,
    NET_SETTLEMENT_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
ORDER BY TXN_ID;

-- GOLD TABLE

CREATE OR REPLACE TABLE GOLD_MERCHANT_SETTLEMENTS (
    MERCHANT_ID NUMBER,
    MERCHANT_NAME VARCHAR,

    TOTAL_APPROVED_GROSS NUMBER(16,2),
    TOTAL_GATEWAY_FEES NUMBER(16,2),
    TOTAL_NET_PAYOUT NUMBER(16,2),

    APPROVED_COUNT NUMBER
);

INSERT INTO GOLD_MERCHANT_SETTLEMENTS (
    MERCHANT_ID,
    MERCHANT_NAME,
    TOTAL_APPROVED_GROSS,
    TOTAL_GATEWAY_FEES,
    TOTAL_NET_PAYOUT,
    APPROVED_COUNT
)
SELECT
    MERCHANT_ID,

    MERCHANT_NAME,

    SUM(GROSS_AMOUNT) AS TOTAL_APPROVED_GROSS,

    SUM(PROCESSING_FEE) AS TOTAL_GATEWAY_FEES,

    SUM(NET_SETTLEMENT_AMOUNT) AS TOTAL_NET_PAYOUT,

    COUNT(*) AS APPROVED_COUNT

FROM SILVER_CLEANED_TRANSACTIONS

WHERE STATUS = 'APPROVED'

GROUP BY
    MERCHANT_ID,
    MERCHANT_NAME;

SELECT
    MERCHANT_ID,
    MERCHANT_NAME,
    TOTAL_APPROVED_GROSS,
    TOTAL_GATEWAY_FEES,
    TOTAL_NET_PAYOUT,
    APPROVED_COUNT
FROM GOLD_MERCHANT_SETTLEMENTS
ORDER BY MERCHANT_ID;

---DATA CORRUPTION & TIME TRAVEL
--VERIFYING THE DATA BEFORE THE DATA IS COURRPTED
SELECT
    TXN_ID,
    MERCHANT_NAME,
    GROSS_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED'
ORDER BY TXN_ID;

-- IF WE ACCIDENTLY UPDATEING THE CLEANED DATA IN SILVER LAYER
UPDATE SILVER_CLEANED_TRANSACTIONS
SET STATUS = 'REFUNDED'
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED';

--- VALIDATING THE COURRPTED DATA
SELECT
    TXN_ID,
    MERCHANT_NAME,
    GROSS_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
ORDER BY TXN_ID;


--Capture the Corruption Query ID
SET CORRUPTION_QUERY_ID = LAST_QUERY_ID();
SELECT $CORRUPTION_QUERY_ID;

---Time Travel Inspection
SELECT
    TXN_ID,
    MERCHANT_NAME,
    GROSS_AMOUNT AS GROSS,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
BEFORE (
    STATEMENT => $CORRUPTION_QUERY_ID
)
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED'
ORDER BY TXN_ID;

SELECT *
FROM SILVER_CLEANED_TRANSACTIONS
AT (
    OFFSET => -60
);

--TIME TRAVEL RECOVERY
CREATE OR REPLACE TEMPORARY TABLE RECOVERY_SNAPSHOT AS
SELECT
    TXN_ID,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
BEFORE (
    STATEMENT => $CORRUPTION_QUERY_ID
)
WHERE MERCHANT_NAME = 'TechZone';

SELECT *
FROM RECOVERY_SNAPSHOT
ORDER BY TXN_ID;

--Recover Silver Using Historical Data
UPDATE SILVER_CLEANED_TRANSACTIONS AS CURRENT_DATA
SET STATUS = RECOVERY.STATUS
FROM RECOVERY_SNAPSHOT AS RECOVERY
WHERE CURRENT_DATA.TXN_ID = RECOVERY.TXN_ID
  AND CURRENT_DATA.MERCHANT_NAME = 'TechZone';

SELECT
    MERCHANT_NAME,

    COUNT_IF(STATUS = 'APPROVED') AS APPROVED_COUNT,

    COUNT_IF(STATUS = 'REFUNDED') AS REFUNDED_COUNT

FROM SILVER_CLEANED_TRANSACTIONS

WHERE MERCHANT_NAME = 'TechZone'

GROUP BY MERCHANT_NAME;

--Verify Individual Transactions

SELECT
    TXN_ID,
    MERCHANT_NAME,
    GROSS_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
ORDER BY TXN_ID;

--END-TO-END RECONCILIATION
--Bronze Gross Total
SELECT
    SUM(RAW_PAYLOAD:amount::NUMBER(14,2)) AS BRONZE_GROSS_SUM
FROM BRONZE_PAYMENT_PAYLOADS;


----SILVER  Gross Total
SELECT
    SUM(GROSS_AMOUNT) AS SILVER_GROSS_SUM
FROM SILVER_CLEANED_TRANSACTIONS;

--GOLD GROSS TOTAL
SELECT
    SUM(TOTAL_APPROVED_GROSS) AS GOLD_GROSS_SUM
FROM GOLD_MERCHANT_SETTLEMENTS;


--Final Reconciliation Query
WITH RECONCILIATION AS (

    SELECT
        (
            SELECT SUM(
                RAW_PAYLOAD:amount::NUMBER(14,2)
            )
            FROM BRONZE_PAYMENT_PAYLOADS
        ) AS BRONZE_GROSS_SUM,

        (
            SELECT SUM(GROSS_AMOUNT)
            FROM SILVER_CLEANED_TRANSACTIONS
        ) AS SILVER_GROSS_SUM,

        (
            SELECT SUM(TOTAL_APPROVED_GROSS)
            FROM GOLD_MERCHANT_SETTLEMENTS
        ) AS GOLD_GROSS_SUM
)

SELECT
    BRONZE_GROSS_SUM,
    SILVER_GROSS_SUM,
    GOLD_GROSS_SUM,

    CASE
        WHEN BRONZE_GROSS_SUM = SILVER_GROSS_SUM
        THEN TRUE
        ELSE FALSE
    END AS DATA_MATCH_FLAG

FROM RECONCILIATION;
