-- Initialize the retail warehouse, database, and schema context.
-- Co-authored with CoCo
CREATE OR REPLACE WAREHOUSE RETAIL4_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE RETAIL4_WH;

CREATE OR REPLACE DATABASE RETAIL4_DW;
USE DATABASE RETAIL4_DW;

CREATE OR REPLACE SCHEMA STAR_SCHEMA;
USE SCHEMA STAR_SCHEMA;
CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_PRODUCT
(
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE NUMBER(12,2)
);

CREATE OR REPLACE TABLE DIM_BRANCH
(
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR(150),
    CITY VARCHAR(100),
    STATE VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_DATE
(
    DATE_ID NUMBER PRIMARY KEY,
    DATE DATE,
    MONTH VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR NUMBER
);

CREATE OR REPLACE TABLE FACT_SALES
(
    SALE_ID NUMBER PRIMARY KEY,

    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,

    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(14,2),

    CONSTRAINT FK_SALES_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_SALES_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_SALES_BRANCH
        FOREIGN KEY (BRANCH_ID)
        REFERENCES DIM_BRANCH(BRANCH_ID),

    CONSTRAINT FK_SALES_DATE
        FOREIGN KEY (DATE_ID)
        REFERENCES DIM_DATE(DATE_ID)
);

show tables

CREATE OR REPLACE STAGE RETAIL_STAGE;
show stages


CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER=1
TRIM_SPACE=TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE;

COPY INTO DIM_CUSTOMER
FROM @RETAIL_STAGE/customers5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';


COPY INTO DIM_PRODUCT
FROM @RETAIL_STAGE/products5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';


COPY INTO DIM_BRANCH
FROM @RETAIL_STAGE/branch5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';


COPY INTO DIM_DATE
FROM @RETAIL_STAGE/dates5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';


COPY INTO FACT_SALES
FROM @RETAIL_STAGE/sales5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';

SELECT COUNT(*) FROM DIM_CUSTOMER;

SELECT COUNT(*) FROM DIM_PRODUCT;

SELECT COUNT(*) FROM DIM_BRANCH;

SELECT COUNT(*) FROM DIM_DATE;

SELECT COUNT(*) FROM FACT_SALES;

SELECT F.CUSTOMER_ID
FROM FACT_SALES F
LEFT JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

SELECT F.PRODUCT_ID
FROM FACT_SALES F
LEFT JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;

SELECT F.BRANCH_ID
FROM FACT_SALES F
LEFT JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
WHERE B.BRANCH_ID IS NULL;


SELECT F.DATE_ID
FROM FACT_SALES F
LEFT JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
WHERE D.DATE_ID IS NULL;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;


SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;


SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE
ORDER BY TOTAL_REVENUE DESC;


SELECT
    B.STATE,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.STATE
ORDER BY TOTAL_REVENUE DESC;

SELECT
    P.CATEGORY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

SELECT
    D.YEAR,
    D.MONTH,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY
    D.YEAR,
    D.MONTH
ORDER BY
    D.YEAR,
    D.MONTH;

SELECT
    D.YEAR,
    D.QUARTER,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY
    D.YEAR,
    D.QUARTER
ORDER BY
    D.YEAR,
    D.QUARTER;


SELECT
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 10;


SELECT
    P.PRODUCT_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;



SELECT
    B.BRANCH_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT
    D.DATE,
    SUM(F.TOTAL_AMOUNT) AS DAILY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY D.DATE
ORDER BY D.DATE;

SELECT
    C.CUSTOMER_NAME,
    COUNT(F.SALE_ID) AS NUMBER_OF_PURCHASES,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SPEND
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_SPEND DESC;


CREATE OR REPLACE VIEW VW_CUSTOMER_REVENUE AS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY,
    C.STATE,
    C.MEMBERSHIP,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY,
    C.STATE,
    C.MEMBERSHIP;


SELECT *
FROM VW_CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;