CREATE OR REPLACE WAREHOUSE RETAIL_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
    show warehouses
    SELECT CURRENT_WAREHOUSE();
    CREATE OR REPLACE DATABASE RETAIL_DW;

USE DATABASE RETAIL_DW;

CREATE OR REPLACE SCHEMA STAR_SCHEMA;

USE SCHEMA STAR_SCHEMA;
CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME STRING,
    CITY STRING,
    STATE STRING,
    MEMBERSHIP STRING
);
CREATE OR REPLACE TABLE DIM_PRODUCT
(
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    BRAND STRING,
    PRICE NUMBER(10,2)
);
CREATE OR REPLACE TABLE DIM_BRANCH
(
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME STRING,
    CITY STRING,
    STATE STRING,
    REGION STRING,
    MANAGER_NAME STRING
);
CREATE OR REPLACE TABLE DIM_DATE
(
    DATE_ID NUMBER PRIMARY KEY,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME STRING,
    WEEK_NO NUMBER,
    MONTH STRING,
    QUARTER STRING,
    YEAR NUMBER,
    IS_WEEKEND STRING
);
CREATE OR REPLACE TABLE FACT_SALES
(
    SALE_ID NUMBER PRIMARY KEY,

    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,

    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2),

    CONSTRAINT FK_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_BRANCH
        FOREIGN KEY (BRANCH_ID)
        REFERENCES DIM_BRANCH(BRANCH_ID),

    CONSTRAINT FK_DATE
        FOREIGN KEY (DATE_ID)
        REFERENCES DIM_DATE(DATE_ID)
);
CREATE OR REPLACE STAGE RETAIL_STAGE;
SHOW STAGES;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER=1
TRIM_SPACE=TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE;

COPY INTO DIM_CUSTOMER
FROM @RETAIL_STAGE/customers5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';


COPY INTO DIM_PRODUCT
FROM @RETAIL_STAGE/products5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';


COPY INTO DIM_BRANCH
FROM @RETAIL_STAGE/branch5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';


COPY INTO DIM_DATE
FROM @RETAIL_STAGE/dates5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';


COPY INTO FACT_SALES
FROM @RETAIL_STAGE/sales5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';

SELECT COUNT(*) FROM DIM_CUSTOMER;
SELECT COUNT(*) FROM DIM_PRODUCT;
SELECT COUNT(*) FROM DIM_BRANCH;
SELECT COUNT(*) FROM DIM_DATE;
SELECT COUNT(*) FROM FACT_SALES;


SELECT
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY REVENUE DESC;


SELECT
    P.PRODUCT_NAME,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY REVENUE DESC;

SELECT
    B.BRANCH_NAME,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.BRANCH_NAME
ORDER BY REVENUE DESC;

SELECT
    B.STATE,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.STATE
ORDER BY REVENUE DESC;

SELECT
    D.MONTH,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
ON F.DATE_ID = D.DATE_ID
GROUP BY D.MONTH
ORDER BY REVENUE DESC;

SELECT
    D.QUARTER,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
ON F.DATE_ID = D.DATE_ID
GROUP BY D.QUARTER;

SELECT
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY REVENUE DESC
LIMIT 10;


SELECT
    P.PRODUCT_NAME,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY REVENUE DESC
LIMIT 10;

SELECT
    P.CATEGORY,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY REVENUE DESC;

SELECT
    B.REGION,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.REGION
ORDER BY REVENUE DESC;


CREATE OR REPLACE VIEW VW_CUSTOMER_REVENUE AS
SELECT
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
ON F.CUSTOMER_ID=C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME;

CREATE OR REPLACE VIEW VW_PRODUCT_REVENUE AS
SELECT
    P.PRODUCT_NAME,
    SUM(F.TOTAL_AMOUNT) REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
ON F.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME;

CREATE OR REPLACE VIEW VW_BRANCH_REVENUE AS
SELECT
    B.BRANCH_NAME,
    SUM(F.TOTAL_AMOUNT) REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
ON F.BRANCH_ID=B.BRANCH_ID
GROUP BY B.BRANCH_NAME;
