CREATE OR REPLACE WAREHOUSE RETAIL6_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
    show warehouses
    SELECT CURRENT_WAREHOUSE();
    CREATE OR REPLACE DATABASE RETAIL6_DW;

USE DATABASE RETAIL6_DW;

CREATE OR REPLACE SCHEMA Snowflake_SCHEMA;

USE SCHEMA Snowflake_SCHEMA;
CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME STRING,
    CITY STRING,
    STATE STRING,
    MEMBERSHIP STRING
);
CREATE OR REPLACE TABLE DIM_PRODUCT
(
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    BRAND STRING,
    PRICE NUMBER(10,2)
);
CREATE OR REPLACE TABLE DIM_BRANCH
(
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME STRING,
    CITY STRING,
    STATE STRING,
    REGION STRING,
    MANAGER_NAME STRING
);
CREATE OR REPLACE TABLE DIM_DATE
(
    DATE_ID NUMBER PRIMARY KEY,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME STRING,
    WEEK_NO NUMBER,
    MONTH STRING,
    QUARTER STRING,
    YEAR NUMBER,
    IS_WEEKEND STRING
);
CREATE OR REPLACE TABLE FACT_SALES
(
    SALE_ID NUMBER PRIMARY KEY,

    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,

    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2),

    CONSTRAINT FK_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_BRANCH
        FOREIGN KEY (BRANCH_ID)
        REFERENCES DIM_BRANCH(BRANCH_ID),

    CONSTRAINT FK_DATE
        FOREIGN KEY (DATE_ID)
        REFERENCES DIM_DATE(DATE_ID)
);
CREATE OR REPLACE STAGE RETAIL6_STAGE;
SHOW STAGES;

LIST @RETAIL6_DW.SNOWFLAKE_SCHEMA.RETAIL6_STAGE;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER=1
TRIM_SPACE=TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE;

COPY INTO DIM_CUSTOMER
FROM @RETAIL6_DW.SNOWFLAKE_SCHEMA.RETAIL6_STAGE/customers5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';


COPY INTO DIM_PRODUCT
FROM @RETAIL6_DW.SNOWFLAKE_SCHEMA.RETAIL6_STAGE/products5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';


COPY INTO DIM_BRANCH
FROM @RETAIL6_DW.SNOWFLAKE_SCHEMA.RETAIL6_STAGE/branch5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';


COPY INTO DIM_DATE
FROM @RETAIL6_DW.SNOWFLAKE_SCHEMA.RETAIL6_STAGE/dates5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';


COPY INTO FACT_SALES
FROM @RETAIL6_DW.SNOWFLAKE_SCHEMA.RETAIL6_STAGE/sales5.csv
FILE_FORMAT=(FORMAT_NAME='CSV_FORMAT')
ON_ERROR='CONTINUE';

SELECT COUNT(*) FROM DIM_CUSTOMER;
SELECT COUNT(*) FROM DIM_PRODUCT;
SELECT BRANCH_ID,
    BRANCH_NAME,
    CITY,
    STATE,
    REGION ,
    MANAGER_NAME FROM DIM_BRANCH;
SELECT COUNT(*) FROM DIM_DATE;
SELECT COUNT(*) FROM FACT_SALES;



CREATE OR REPLACE TABLE STG_CUSTOMERS
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);

CREATE OR REPLACE TABLE STG_PRODUCTS
(
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE NUMBER(12,2)
);


CREATE OR REPLACE TABLE STG_BRANCHES
(
    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR(150),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50),
    MANAGER_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE STG_CALENDAR
(
    DATE_ID NUMBER,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER,
    MONTH VARCHAR(20),
    QUARTER VARCHAR(20),
    YEAR NUMBER,
    IS_WEEKEND VARCHAR(10)
);


CREATE OR REPLACE TABLE STG_SALES
(
    SALE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(14,2)
);

COPY INTO RETAIL6_DW.SNOWFLAKE_SCHEMA.STG_CUSTOMERS
FROM @RETAIL6_DW.SNOWFLAKE_SCHEMA.RETAIL6_STAGE/customers5.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL6_DW.SNOWFLAKE_SCHEMA.CSV_FORMAT')
ON_ERROR = 'CONTINUE';

COPY INTO RETAIL6_DW.SNOWFLAKE_SCHEMA.STG_PRODUCTS
FROM @RETAIL6_DW.SNOWFLAKE_SCHEMA.RETAIL6_STAGE/products5.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL6_DW.SNOWFLAKE_SCHEMA.CSV_FORMAT')
ON_ERROR = 'CONTINUE';

COPY INTO RETAIL6_DW.SNOWFLAKE_SCHEMA.STG_BRANCHES
FROM @RETAIL6_DW.SNOWFLAKE_SCHEMA.RETAIL6_STAGE/branch5.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL6_DW.SNOWFLAKE_SCHEMA.CSV_FORMAT')
ON_ERROR = 'CONTINUE';

COPY INTO RETAIL6_DW.SNOWFLAKE_SCHEMA.STG_CALENDAR
FROM @RETAIL6_DW.SNOWFLAKE_SCHEMA.RETAIL6_STAGE/dates5.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL6_DW.SNOWFLAKE_SCHEMA.CSV_FORMAT')
ON_ERROR = 'CONTINUE';

COPY INTO RETAIL6_DW.SNOWFLAKE_SCHEMA.STG_SALES
FROM @RETAIL6_DW.SNOWFLAKE_SCHEMA.RETAIL6_STAGE/sales5.csv
FILE_FORMAT = (FORMAT_NAME = 'RETAIL6_DW.SNOWFLAKE_SCHEMA.CSV_FORMAT')
ON_ERROR = 'CONTINUE';




select count(*) from STG_PRODUCTS;
select count(*) from STG_CUSTOMERS
 SELECT BRANCH_ID,
    BRANCH_NAME,
    CITY,
    STATE,
    REGION ,
    MANAGER_NAME FROM  STG_BRANCHES;
select count(*) from STG_CALENDAR;
select count(*) from STG_SALES;
SELECT * FROM STG_SALES
ORDER BY SALE_ID;

CREATE OR REPLACE TABLE DIM_REGION
(
    REGION_ID NUMBER PRIMARY KEY,
    REGION_NAME STRING
);


INSERT INTO DIM_REGION
SELECT
    ROW_NUMBER() OVER (ORDER BY REGION) AS REGION_ID,
    REGION
FROM
(
    SELECT DISTINCT REGION
    FROM STG_BRANCHES
);

SELECT * FROM DIM_REGION
ORDER BY REGION_ID;

CREATE OR REPLACE TABLE DIM_STATE
(
    STATE_ID NUMBER PRIMARY KEY,
    STATE_NAME STRING,
    REGION_ID NUMBER,
    
    CONSTRAINT FK_STATE_REGION
        FOREIGN KEY (REGION_ID)
        REFERENCES DIM_REGION(REGION_ID)
);

INSERT INTO DIM_STATE
(
    STATE_ID,
    STATE_NAME,
    REGION_ID
)
SELECT
    ROW_NUMBER() OVER (ORDER BY STATE_NAME),
    STATE_NAME,
    REGION_ID
FROM
(
    SELECT
        STATE_NAME,
        MAX(REGION_ID) AS REGION_ID
    FROM
    (
        SELECT
            STATE AS STATE_NAME,
            r.REGION_ID
        FROM STG_BRANCHES b
        JOIN DIM_REGION r
            ON b.REGION = r.REGION_NAME

        UNION ALL

        SELECT
            STATE AS STATE_NAME,
            NULL AS REGION_ID
        FROM STG_CUSTOMERS
    )
    GROUP BY STATE_NAME
);

SELECT *
FROM DIM_STATE
ORDER BY STATE_ID;

CREATE OR REPLACE TABLE DIM_CITY
(
    CITY_ID NUMBER PRIMARY KEY,
    CITY_NAME STRING,
    STATE_ID NUMBER,

    CONSTRAINT FK_CITY_STATE
        FOREIGN KEY (STATE_ID)
        REFERENCES DIM_STATE(STATE_ID)
);

INSERT INTO DIM_CITY
(
    CITY_ID,
    CITY_NAME,
    STATE_ID
)
SELECT
    ROW_NUMBER() OVER (ORDER BY CITY_NAME),
    CITY_NAME,
    STATE_ID
FROM
(
    SELECT DISTINCT
        c.CITY AS CITY_NAME,
        s.STATE_ID
    FROM STG_CUSTOMERS c
    JOIN DIM_STATE s
        ON c.STATE = s.STATE_NAME

    UNION

    SELECT DISTINCT
        b.CITY AS CITY_NAME,
        s.STATE_ID
    FROM STG_BRANCHES b
    JOIN DIM_STATE s
        ON b.STATE = s.STATE_NAME
);

SELECT * FROM DIM_CITY
ORDER BY CITY_ID;


CREATE OR REPLACE TABLE DIM_CATEGORY
(
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME STRING
);

INSERT INTO DIM_CATEGORY
SELECT
    ROW_NUMBER() OVER (ORDER BY CATEGORY) AS CATEGORY_ID,
    CATEGORY
FROM
(
    SELECT DISTINCT CATEGORY
    FROM STG_PRODUCTS
);
SELECT * FROM DIM_CATEGORY;

CREATE OR REPLACE TABLE DIM_BRAND
(
    BRAND_ID NUMBER PRIMARY KEY,
    BRAND_NAME STRING,
    CATEGORY_ID NUMBER,

    CONSTRAINT FK_BRAND_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES DIM_CATEGORY(CATEGORY_ID)
);

INSERT INTO DIM_BRAND
(
    BRAND_ID,
    BRAND_NAME,
    CATEGORY_ID
)
SELECT
    ROW_NUMBER() OVER (ORDER BY p.BRAND),
    p.BRAND,
    c.CATEGORY_ID
FROM
(
    SELECT DISTINCT
        BRAND,
        CATEGORY
    FROM STG_PRODUCTS
) p
JOIN DIM_CATEGORY c
    ON p.CATEGORY = c.CATEGORY_NAME;

SELECT *
FROM DIM_BRAND
ORDER BY BRAND_ID;

CREATE OR REPLACE TABLE DIM_YEAR
(
    YEAR_ID NUMBER PRIMARY KEY,
    YEAR_VALUE NUMBER
);

INSERT INTO DIM_YEAR
SELECT
    ROW_NUMBER() OVER (ORDER BY YEAR),
    YEAR
FROM
(
    SELECT DISTINCT YEAR
    FROM STG_CALENDAR
);

CREATE OR REPLACE TABLE DIM_QUARTER
(
    QUARTER_ID NUMBER PRIMARY KEY,
    QUARTER_NAME STRING,
    YEAR_ID NUMBER,

    CONSTRAINT FK_QUARTER_YEAR
        FOREIGN KEY (YEAR_ID)
        REFERENCES DIM_YEAR(YEAR_ID)
);

INSERT INTO DIM_QUARTER
(
    QUARTER_ID,
    QUARTER_NAME,
    YEAR_ID
)
SELECT DISTINCT
    c.YEAR * 10 +
    CAST(SUBSTR(c.QUARTER, 2) AS NUMBER) AS QUARTER_ID,

    c.QUARTER,

    y.YEAR_ID
FROM STG_CALENDAR c
JOIN DIM_YEAR y
    ON c.YEAR = y.YEAR_VALUE;


CREATE OR REPLACE TABLE DIM_MONTH
(
    MONTH_ID NUMBER PRIMARY KEY,
    MONTH_NAME STRING,
    MONTH_NUMBER NUMBER,
    QUARTER_ID NUMBER
);

INSERT INTO DIM_MONTH
(
    MONTH_ID,
    MONTH_NAME,
    MONTH_NUMBER,
    QUARTER_ID
)
SELECT DISTINCT

    YEAR(DATE) * 100 + MONTH(DATE) AS MONTH_ID,

    MONTH,

    MONTH(DATE),

    YEAR(DATE) * 10 +
    CAST(SUBSTR(QUARTER, 2) AS NUMBER) AS QUARTER_ID

FROM STG_CALENDAR;

SELECT *
FROM DIM_MONTH;

--PHASE 4 — Normalize DIM_Customer
DROP TABLE DIM_CUSTOMER;

CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME STRING,
    CITY_ID NUMBER,
    MEMBERSHIP STRING,

    CONSTRAINT FK_CUSTOMER_CITY
        FOREIGN KEY (CITY_ID)
        REFERENCES DIM_CITY(CITY_ID)
);

INSERT INTO DIM_CUSTOMER
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY_ID,
    MEMBERSHIP
)
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    ci.CITY_ID,
    c.MEMBERSHIP
FROM STG_CUSTOMERS c
JOIN DIM_CITY ci
    ON c.CITY = ci.CITY_NAME;

SELECT *
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;


---PHASE 4 — Normalize DIM_PRODUCT
DROP TABLE DIM_PRODUCT;
CREATE OR REPLACE TABLE DIM_PRODUCT
(
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME STRING,
    BRAND_ID NUMBER,
    PRICE NUMBER(10,2),

    CONSTRAINT FK_PRODUCT_BRAND
        FOREIGN KEY (BRAND_ID)
        REFERENCES DIM_BRAND(BRAND_ID)
);

INSERT INTO DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    BRAND_ID,
    PRICE
)
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    b.BRAND_ID,
    p.PRICE
FROM STG_PRODUCTS p
JOIN DIM_BRAND b
    ON p.BRAND = b.BRAND_NAME;

SELECT *
FROM DIM_PRODUCT
ORDER BY PRODUCT_ID;

--phase 4 Normalize DIM_BRANCH
DROP TABLE DIM_BRANCH;
CREATE OR REPLACE TABLE DIM_BRANCH
(
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME STRING,
    CITY_ID NUMBER,
    MANAGER_NAME STRING,

    CONSTRAINT FK_BRANCH_CITY
        FOREIGN KEY (CITY_ID)
        REFERENCES DIM_CITY(CITY_ID)
);

INSERT INTO DIM_BRANCH
(
    BRANCH_ID,
    BRANCH_NAME,
    CITY_ID,
    MANAGER_NAME
)
SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    c.CITY_ID,
    b.MANAGER_NAME
FROM STG_BRANCHES b
JOIN DIM_CITY c
    ON b.CITY = c.CITY_NAME;
SELECT *
FROM DIM_BRANCH
ORDER BY BRANCH_ID;

--PHASE 4 — Normalize DIM_DATE
DROP TABLE DIM_DATE;
CREATE OR REPLACE TABLE DIM_DATE
(
    DATE_ID NUMBER PRIMARY KEY,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME STRING,
    WEEK_NO NUMBER,
    MONTH_ID NUMBER,
    IS_WEEKEND STRING,

    CONSTRAINT FK_DATE_MONTH
        FOREIGN KEY (MONTH_ID)
        REFERENCES DIM_MONTH(MONTH_ID)
);
INSERT INTO DIM_DATE
(
    DATE_ID,
    DATE,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH_ID,
    IS_WEEKEND
)
SELECT
    c.DATE_ID,
    c.DATE,
    c.DAY,
    c.DAY_NAME,
    c.WEEK_NO,
    YEAR(c.DATE) * 100 + MONTH(c.DATE) AS MONTH_ID,
    c.IS_WEEKEND
FROM STG_CALENDAR c;

SELECT *
FROM DIM_DATE
ORDER BY DATE_ID;


--PHASE 5 — Rebuild FACT_SALES relationships
TRUNCATE TABLE FACT_SALES;
INSERT INTO FACT_SALES
(
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
FROM STG_SALES;
SELECT *
FROM FACT_SALES
ORDER BY SALE_ID;
--- Validating foreign key relationship

SELECT COUNT(*) AS INVALID_CUSTOMERS
FROM FACT_SALES f
LEFT JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
WHERE c.CUSTOMER_ID IS NULL;

SELECT COUNT(*) AS INVALID_PRODUCTS
FROM FACT_SALES f
LEFT JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
WHERE p.PRODUCT_ID IS NULL;

SELECT COUNT(*) AS INVALID_BRANCHES
FROM FACT_SALES f
LEFT JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
WHERE b.BRANCH_ID IS NULL;

SELECT COUNT(*) AS INVALID_DATES
FROM FACT_SALES f
LEFT JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
WHERE d.DATE_ID IS NULL;

--Validate the complete hierarchy
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    ci.CITY_NAME,
    s.STATE_NAME,
    c.MEMBERSHIP
FROM DIM_CUSTOMER c
JOIN DIM_CITY ci
    ON c.CITY_ID = ci.CITY_ID
JOIN DIM_STATE s
    ON ci.STATE_ID = s.STATE_ID
ORDER BY c.CUSTOMER_ID;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    b.BRAND_NAME,
    c.CATEGORY_NAME,
    p.PRICE
FROM DIM_PRODUCT p
JOIN DIM_BRAND b
    ON p.BRAND_ID = b.BRAND_ID
JOIN DIM_CATEGORY c
    ON b.CATEGORY_ID = c.CATEGORY_ID
ORDER BY p.PRODUCT_ID;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    ci.CITY_NAME,
    s.STATE_NAME,
    r.REGION_NAME,
    b.MANAGER_NAME
FROM DIM_BRANCH b
JOIN DIM_CITY ci
    ON b.CITY_ID = ci.CITY_ID
JOIN DIM_STATE s
    ON ci.STATE_ID = s.STATE_ID
JOIN DIM_REGION r
    ON s.REGION_ID = r.REGION_ID
ORDER BY b.BRANCH_ID;

SELECT
    d.DATE_ID,
    d.DATE,
    m.MONTH_NAME,
    q.QUARTER_NAME,
    y.YEAR_VALUE
FROM DIM_DATE d
JOIN DIM_MONTH m
    ON d.MONTH_ID = m.MONTH_ID
JOIN DIM_QUARTER q
    ON m.QUARTER_ID = q.QUARTER_ID
JOIN DIM_YEAR y
    ON q.YEAR_ID = y.YEAR_ID
ORDER BY d.DATE_ID;

---PHASE 6 — Business Reports
--Report 1 — Customer-wise Sales
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;

--Report 2 — Product-wise Revenue
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

--Report 3 — Brand-wise Revenue
SELECT
    b.BRAND_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
JOIN DIM_BRAND b
    ON p.BRAND_ID = b.BRAND_ID
GROUP BY b.BRAND_NAME
ORDER BY TOTAL_REVENUE DESC;

--Report 4 — Category-wise Revenue
SELECT
    c.CATEGORY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
JOIN DIM_BRAND b
    ON p.BRAND_ID = b.BRAND_ID
JOIN DIM_CATEGORY c
    ON b.CATEGORY_ID = c.CATEGORY_ID
GROUP BY c.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;

--Report 5 — City-wise Sales
SELECT
    ci.CITY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
JOIN DIM_CITY ci
    ON c.CITY_ID = ci.CITY_ID
GROUP BY ci.CITY_NAME
ORDER BY TOTAL_REVENUE DESC;

--Report 6 — State-wise Revenue
SELECT
    s.STATE_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
JOIN DIM_CITY ci
    ON c.CITY_ID = ci.CITY_ID
JOIN DIM_STATE s
    ON ci.STATE_ID = s.STATE_ID
GROUP BY s.STATE_NAME
ORDER BY TOTAL_REVENUE DESC;

--Report 7 — Region-wise Revenue
SELECT
    r.REGION_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
JOIN DIM_CITY ci
    ON b.CITY_ID = ci.CITY_ID
JOIN DIM_STATE s
    ON ci.STATE_ID = s.STATE_ID
JOIN DIM_REGION r
    ON s.REGION_ID = r.REGION_ID
GROUP BY r.REGION_NAME
ORDER BY TOTAL_REVENUE DESC;

--Report 8 — Monthly Revenue
SELECT
    y.YEAR_VALUE,
    q.QUARTER_NAME,
    m.MONTH_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
JOIN DIM_MONTH m
    ON d.MONTH_ID = m.MONTH_ID
JOIN DIM_QUARTER q
    ON m.QUARTER_ID = q.QUARTER_ID
JOIN DIM_YEAR y
    ON q.YEAR_ID = y.YEAR_ID
GROUP BY
    y.YEAR_VALUE,
    q.QUARTER_NAME,
    m.MONTH_NAME
ORDER BY
    y.YEAR_VALUE,
    m.MONTH_NAME;

--Report 9 — Quarterly Revenue
SELECT
    y.YEAR_VALUE,
    q.QUARTER_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
JOIN DIM_MONTH m
    ON d.MONTH_ID = m.MONTH_ID
JOIN DIM_QUARTER q
    ON m.QUARTER_ID = q.QUARTER_ID
JOIN DIM_YEAR y
    ON q.YEAR_ID = y.YEAR_ID
GROUP BY
    y.YEAR_VALUE,
    q.QUARTER_NAME
ORDER BY
    y.YEAR_VALUE,
    q.QUARTER_NAME;
--top 10 customers
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;
-- top 10 products
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;
-- top 10 branches
SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

--Customer Purchase Trend
SELECT
    c.CUSTOMER_NAME,
    d.DATE,
    SUM(f.TOTAL_AMOUNT) AS DAILY_REVENUE
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY
    c.CUSTOMER_NAME,
    d.DATE
ORDER BY
    c.CUSTOMER_NAME,
    d.DATE;
--Product Performance Dashboard Query
SELECT
    p.PRODUCT_NAME,
    b.BRAND_NAME,
    c.CATEGORY_NAME,
    SUM(f.QUANTITY) AS TOTAL_UNITS_SOLD,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(f.TOTAL_AMOUNT) AS AVG_SALE_AMOUNT
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
JOIN DIM_BRAND b
    ON p.BRAND_ID = b.BRAND_ID
JOIN DIM_CATEGORY c
    ON b.CATEGORY_ID = c.CATEGORY_ID
GROUP BY
    p.PRODUCT_NAME,
    b.BRAND_NAME,
    c.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;
--Regional Sales Dashboard
SELECT
    r.REGION_NAME,
    s.STATE_NAME,
    ci.CITY_NAME,
    b.BRANCH_NAME,
    SUM(f.QUANTITY) AS TOTAL_UNITS,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
JOIN DIM_CITY ci
    ON b.CITY_ID = ci.CITY_ID
JOIN DIM_STATE s
    ON ci.STATE_ID = s.STATE_ID
JOIN DIM_REGION r
    ON s.REGION_ID = r.REGION_ID
GROUP BY
    r.REGION_NAME,
    s.STATE_NAME,
    ci.CITY_NAME,
    b.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC;
--  phase -8 Final row-count validation
SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM DIM_CUSTOMER

UNION ALL

SELECT 'DIM_PRODUCT', COUNT(*)
FROM DIM_PRODUCT

UNION ALL

SELECT 'DIM_BRANCH', COUNT(*)
FROM DIM_BRANCH

UNION ALL

SELECT 'DIM_DATE', COUNT(*)
FROM DIM_DATE

UNION ALL

SELECT 'DIM_CITY', COUNT(*)
FROM DIM_CITY

UNION ALL

SELECT 'DIM_STATE', COUNT(*)
FROM DIM_STATE

UNION ALL

SELECT 'DIM_REGION', COUNT(*)
FROM DIM_REGION

UNION ALL

SELECT 'DIM_CATEGORY', COUNT(*)
FROM DIM_CATEGORY

UNION ALL

SELECT 'DIM_BRAND', COUNT(*)
FROM DIM_BRAND

UNION ALL

SELECT 'DIM_MONTH', COUNT(*)
FROM DIM_MONTH

UNION ALL

SELECT 'DIM_QUARTER', COUNT(*)
FROM DIM_QUARTER

UNION ALL

SELECT 'DIM_YEAR', COUNT(*)
FROM DIM_YEAR

UNION ALL

SELECT 'FACT_SALES', COUNT(*)
FROM FACT_SALES;