CREATE OR REPLACE WAREHOUSE CUSTOMER_PROFILE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
create or replace database CUSTOMER_PROFILE_DB;
CREATE OR REPLACE SCHEMA SCD_SCHEMA;
use schema SCD_SCHEMA;
CREATE OR REPLACE STAGE CUSTOMER_STAGE;
show stages;
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER=1
TRIM_SPACE=TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE;
show FILE FORMATS;

CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);
LIST @CUSTOMER_STAGE;
COPY INTO DIM_CUSTOMER
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_STAGE/customer_intial.csv
FILE_FORMAT = (
    FORMAT_NAME = 'CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';
SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM DIM_CUSTOMER;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);
LIST @CUSTOMER_STAGE;
COPY INTO CUSTOMER_UPDATES
FROM @CUSTOMER_STAGE/customer_update.csv
FILE_FORMAT = (
    FORMAT_NAME =  'CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';
SELECT COUNT(*) AS RECORDS_RECEIVED
FROM CUSTOMER_UPDATES;
SELECT *
FROM CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;

-- Tak6
SELECT
    d.CUSTOMER_ID,
    d.CITY AS OLD_CITY,
    u.CITY AS NEW_CITY,
    d.MEMBERSHIP AS OLD_MEMBERSHIP,
    u.MEMBERSHIP AS NEW_MEMBERSHIP
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE
       NVL(d.CITY, '') <> NVL(u.CITY, '')
    OR NVL(d.STATE, '') <> NVL(u.STATE, '')
    OR NVL(d.MEMBERSHIP, '') <> NVL(u.MEMBERSHIP, '')
    OR NVL(d.SEGMENT, '') <> NVL(u.SEGMENT, '')
ORDER BY d.CUSTOMER_ID;

-- Task 7 All changes of city, membership, state
SELECT
    d.CUSTOMER_ID,
    'CITY' AS ATTRIBUTE,
    d.CITY AS OLD_VALUE,
    u.CITY AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE NVL(d.CITY, '') <> NVL(u.CITY, '')

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'STATE' AS ATTRIBUTE,
    d.STATE AS OLD_VALUE,
    u.STATE AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE NVL(d.STATE, '') <> NVL(u.STATE, '')

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'MEMBERSHIP' AS ATTRIBUTE,
    d.MEMBERSHIP AS OLD_VALUE,
    u.MEMBERSHIP AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE NVL(d.MEMBERSHIP, '') <> NVL(u.MEMBERSHIP, '')

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'SEGMENT' AS ATTRIBUTE,
    d.SEGMENT AS OLD_VALUE,
    u.SEGMENT AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE NVL(d.SEGMENT, '') <> NVL(u.SEGMENT, '')

ORDER BY CUSTOMER_ID, ATTRIBUTE;

--PHASE 19 — Update DIM_CUSTOMER
UPDATE DIM_CUSTOMER d
SET
    CUSTOMER_NAME = u.CUSTOMER_NAME,
    CITY = u.CITY,
    STATE = u.STATE,
    MEMBERSHIP = u.MEMBERSHIP,
    SEGMENT = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;
SELECT COUNT(*)
FROM DIM_CUSTOMER;
---PHASE 20 — Display Updated Dimension
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

--PHASE 21 — Demonstrate Historical Data Loss
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;

--HASE 22 — Prove the Historical Information Is Gone
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;
--PHASE 23 — Final Project Validation

SELECT COUNT(*) AS UPDATE_COUNT
FROM  DIM_CUSTOMER;

SELECT COUNT(*) AS UPDATE_COUNT
FROM CUSTOMER_UPDATES;

SELECT *
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;