CREATE OR REPLACE WAREHOUSE CUSTOMER_HISTORY_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
create or replace database CUSTOMER_PROFILE1_DB;
CREATE OR REPLACE SCHEMA SCD_SCHEMA;
use schema SCD_SCHEMA;
CREATE OR REPLACE STAGE CUSTOMER_STAGE;
show stages;
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER=1
TRIM_SPACE=TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE;
show FILE FORMATS;
LIST @CUSTOMER_STAGE;
CREATE OR REPLACE TABLE DIM_CUSTOMER_T1
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);
COPY INTO DIM_CUSTOMER_T1
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_STAGE/customer_intial.csv
FILE_FORMAT = (
    FORMAT_NAME = 'CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';
select count(*) from DIM_CUSTOMER_T1;
select * from DIM_CUSTOMER_T1 order by CUSTOMER_ID;


CREATE OR REPLACE TABLE CUSTOMER_UPDATES
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);
COPY INTO CUSTOMER_UPDATES
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_STAGE/customer_update.csv
FILE_FORMAT = (
    FORMAT_NAME = 'CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';
select count(*) from customer_updates;
select * from customer_updates order by customer_id;

UPDATE DIM_CUSTOMER_T1 d
SET
    CUSTOMER_NAME = u.CUSTOMER_NAME,
    CITY = u.CITY,
    STATE = u.STATE,
    MEMBERSHIP = u.MEMBERSHIP,
    SEGMENT = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;

--TASK 5 — Display Type 1 Result
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_T1
ORDER BY CUSTOMER_ID;

--TASK 6 — Demonstrate Type 1 History Loss
SELECT
    CUSTOMER_ID,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER_T1
WHERE CUSTOMER_ID = 101;

--TASK 7 — Create SCD Type 2 Table
CREATE OR REPLACE TABLE DIM_CUSTOMER_T2
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

SELECT COUNT(*) AS TOTAL_RECORDS
FROM DIM_CUSTOMER_T2;

--TASK 9 — Load Initial Type 2 Records
INSERT INTO DIM_CUSTOMER_T2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    '2026-01-01'::DATE,
    '9999-12-31'::DATE,
    TRUE
FROM DIM_CUSTOMER_T1;
SELECT COUNT(*) AS TOTAL_RECORDS
FROM DIM_CUSTOMER_T2;

SELECT COUNT(*) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_T2
WHERE IS_CURRENT = TRUE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_T2
ORDER BY CUSTOMER_ID;

--TASK 10 — Apply Type 2 Changes
UPDATE DIM_CUSTOMER_T2 d
SET
    EXPIRY_DATE = u.EFFECTIVE_DATE - 1,
    IS_CURRENT = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND u.CUSTOMER_ID = 101
  AND d.IS_CURRENT = TRUE;

SELECT
    CUSTOMER_ID,
    CITY,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_T2
WHERE CUSTOMER_ID = 101;

--Insert new version
INSERT INTO DIM_CUSTOMER_T2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_UPDATES
WHERE CUSTOMER_ID = 101;


SELECT
    CUSTOMER_ID,
    CITY,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_T2
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

---TASK 12 — Customer 103 Type 2 Change
UPDATE DIM_CUSTOMER_T2 d
SET
    EXPIRY_DATE = u.EFFECTIVE_DATE - 1,
    IS_CURRENT = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND u.CUSTOMER_ID = 103
  AND d.IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_T2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_UPDATES
WHERE CUSTOMER_ID = 103;

SELECT
    CUSTOMER_ID,
    CITY,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_T2
WHERE CUSTOMER_ID = 103
ORDER BY EFFECTIVE_DATE;


--TASK 13 — Customer 104 Type 2 Change
UPDATE DIM_CUSTOMER_T2 d
SET
    EXPIRY_DATE = u.EFFECTIVE_DATE - 1,
    IS_CURRENT = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND u.CUSTOMER_ID = 104
  AND d.IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_T2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_UPDATES
WHERE CUSTOMER_ID = 104;

SELECT
    CUSTOMER_ID,
    CITY,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_T2
WHERE CUSTOMER_ID = 104
ORDER BY EFFECTIVE_DATE;


--TASK 14 — Display Complete Type 2 History
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_T2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

--TASK 15 — Display Current Customer Records

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_T2
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

--TASK 16 — Historical Customer Analysis

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MEMBERSHIP,
    CITY,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_T2
WHERE CUSTOMER_ID = 102
  AND '2026-03-15'::DATE >= EFFECTIVE_DATE
  AND '2026-03-15'::DATE <= EXPIRY_DATE;

--TASK 17 — Compare Type 1 vs Type 2

SELECT
    'Old value preserved?' AS FEATURE,
    'No' AS TYPE_1,
    'Yes' AS TYPE_2

UNION ALL

SELECT
    'New row created?',
    'No',
    'Yes'

UNION ALL

SELECT
    'Historical analysis?',
    'No',
    'Yes'

UNION ALL

SELECT
    'Effective Date',
    'No',
    'Yes'

UNION ALL

SELECT
    'Expiry Date',
    'No',
    'Yes'

UNION ALL

SELECT
    'IS_CURRENT',
    'No',
    'Yes'

UNION ALL

SELECT
    'Storage required',
    'Lower',
    'Higher';


---TASK 18 — Final Validation
SELECT COUNT(*) AS SCD_TYPE_1_RECORD_COUNT
FROM DIM_CUSTOMER_T1;

SELECT COUNT(*) AS SCD_TYPE_2_RECORD_COUNT
FROM DIM_CUSTOMER_T2;

SELECT COUNT(*) AS SCD_TYPE_2_CURRENT_RECORD_COUNT
FROM DIM_CUSTOMER_T2
WHERE IS_CURRENT = TRUE;

SELECT COUNT(*) AS SCD_TYPE_2_HISTORICAL_RECORD_COUNT
FROM DIM_CUSTOMER_T2
WHERE IS_CURRENT = FALSE;