

CREATE OR REPLACE WAREHOUSE PROJECT_19C_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE PROJECT_19C_WH;


CREATE OR REPLACE DATABASE PROJECT_19C_DB;

CREATE OR REPLACE SCHEMA PROJECT_19C_DB.DATA_MODELING;

USE DATABASE PROJECT_19C_DB;
USE SCHEMA DATA_MODELING;


CREATE OR REPLACE TABLE RAW_WIRE_TRANSFERS
(
    TXN_ID          VARCHAR(30),
    TXN_DATE        DATE,
    SENDER_ACC      VARCHAR(30),
    RECEIVER_ACC    VARCHAR(30),
    AMOUNT          NUMBER(18,2),
    FEE             NUMBER(18,2),
    CURRENCY_RATE   NUMBER(10,4),
    AUTH_METHOD     VARCHAR(30),
    RISK_FLAG       VARCHAR(20),
    TRANSFER_TYPE   VARCHAR(30)
);

INSERT INTO RAW_WIRE_TRANSFERS VALUES
('TXN-9001','2026-08-20','ACC-101','ACC-801',100000.00,50.00,1.00,'2FA','LOW','DOMESTIC'),
('TXN-9002','2026-08-20','ACC-102','ACC-901',450000.00,250.00,0.85,'BIOMETRIC','HIGH','INTERNATIONAL'),
('TXN-9003','2026-08-21','ACC-103','ACC-802',75000.00,30.00,1.00,'2FA','LOW','DOMESTIC'),
('TXN-9004','2026-08-21','ACC-101','ACC-902',1200000.00,500.00,0.92,'HARD_TOKEN','HIGH','INTERNATIONAL'),
('TXN-9005','2026-08-22','ACC-104','ACC-803',25000.00,15.00,1.00,'2FA','LOW','DOMESTIC'),
('TXN-9006','2026-08-22','ACC-105','ACC-904',600000.00,300.00,0.85,'BIOMETRIC','MEDIUM','INTERNATIONAL'),
('TXN-9007','2026-08-23','ACC-102','ACC-801',89000.00,40.00,1.00,'2FA','LOW','DOMESTIC');


CREATE OR REPLACE TABLE RAW_VAULT_CASH
(
    SNAPSHOT_DATE       DATE,
    VAULT_ID            VARCHAR(30),
    CURRENCY_CODE       VARCHAR(10),
    OPENING_BALANCE     NUMBER(18,2),
    CLOSING_BALANCE     NUMBER(18,2),
    RESERVE_RATIO_PCT   NUMBER(10,4)
);

INSERT INTO RAW_VAULT_CASH VALUES
('2026-08-24','VLT-NY','USD',5000000.00,5200000.00,0.15),
('2026-08-24','VLT-LDN','GBP',3000000.00,2800000.00,0.18),
('2026-08-24','VLT-SGP','SGD',8000000.00,8100000.00,0.12),
('2026-08-25','VLT-NY','USD',5200000.00,4900000.00,0.15),
('2026-08-25','VLT-LDN','GBP',2800000.00,3100000.00,0.18),
('2026-08-25','VLT-SGP','SGD',8100000.00,8400000.00,0.12);



CREATE OR REPLACE TABLE RAW_CREDIT_LIFECYCLES
(
    APP_ID               VARCHAR(30),
    SUBMISSION_DATE      DATE,
    UNDERWRITE_DATE      DATE,
    RISK_APPROVAL_DATE   DATE,
    DISBURSEMENT_DATE    DATE
);

INSERT INTO RAW_CREDIT_LIFECYCLES VALUES
('APP-401','2026-08-01','2026-08-03','2026-08-05','2026-08-07'),
('APP-402','2026-08-05','2026-08-08','2026-08-12','2026-08-15'),
('APP-403','2026-08-10','2026-08-12','2026-08-18',NULL),
('APP-404','2026-08-15','2026-08-19',NULL,NULL),
('APP-405','2026-08-20',NULL,NULL,NULL);



CREATE OR REPLACE TABLE RAW_AUDIT_COVERAGE
(
    AUDIT_YEAR          NUMBER(4),
    QUARTER             VARCHAR(5),
    ACCOUNT_ID          VARCHAR(30),
    AUDITOR_FIRM        VARCHAR(50),
    COMPLIANCE_STATUS   VARCHAR(30)
);

INSERT INTO RAW_AUDIT_COVERAGE VALUES
(2026,'Q1','ACC-101','Deloitte','VERIFIED'),
(2026,'Q1','ACC-102','PwC','FLAGGED'),
(2026,'Q1','ACC-103','EY','VERIFIED'),
(2026,'Q2','ACC-101','Deloitte','VERIFIED'),
(2026,'Q2','ACC-104','KPMG','VERIFIED'),
(2026,'Q2','ACC-105','PwC','FLAGGED');


 --TASK 1: JUNK DIMENSION

-- Attributes:
    --AUTH_METHOD
     --RISK_FLAG
     --TRANSFER_TYPE



CREATE OR REPLACE TABLE DIM_WIRE_ATTRIBUTES
(
    ATTRIBUTE_SK      NUMBER PRIMARY KEY,
    AUTH_METHOD       VARCHAR(30),
    RISK_FLAG         VARCHAR(20),
    TRANSFER_TYPE     VARCHAR(30)
);

INSERT INTO DIM_WIRE_ATTRIBUTES
(
    ATTRIBUTE_SK,
    AUTH_METHOD,
    RISK_FLAG,
    TRANSFER_TYPE
)
SELECT
    ROW_NUMBER() OVER
    (
        ORDER BY
            AUTH_METHOD,
            RISK_FLAG,
            TRANSFER_TYPE
    ) AS ATTRIBUTE_SK,

    AUTH_METHOD,
    RISK_FLAG,
    TRANSFER_TYPE

FROM
(
    SELECT DISTINCT
        AUTH_METHOD,
        RISK_FLAG,
        TRANSFER_TYPE
    FROM RAW_WIRE_TRANSFERS
);


 --VALIDATE TASK 1
 
SELECT *
FROM DIM_WIRE_ATTRIBUTES
ORDER BY ATTRIBUTE_SK;


 --TASK 2: TRANSACTION FACT + DEGENERATE DIMENSION


CREATE OR REPLACE TABLE FACT_WIRE_TRANSFERS
(
    TXN_ID            VARCHAR(30),
    TXN_DATE          DATE,
    SENDER_ACC        VARCHAR(30),
    RECEIVER_ACC      VARCHAR(30),

    ATTRIBUTE_SK      NUMBER,

    AMOUNT            NUMBER(18,2),
    FEE               NUMBER(18,2),
    CURRENCY_RATE     NUMBER(10,4),

    BASE_AMOUNT_USD   NUMBER(18,2),
    NET_TRANSFER_VAL  NUMBER(18,2)
);

INSERT INTO FACT_WIRE_TRANSFERS
(
    TXN_ID,
    TXN_DATE,
    SENDER_ACC,
    RECEIVER_ACC,
    ATTRIBUTE_SK,
    AMOUNT,
    FEE,
    CURRENCY_RATE,
    BASE_AMOUNT_USD,
    NET_TRANSFER_VAL
)
SELECT
    r.TXN_ID,
    r.TXN_DATE,
    r.SENDER_ACC,
    r.RECEIVER_ACC,

    d.ATTRIBUTE_SK,

    r.AMOUNT,
    r.FEE,
    r.CURRENCY_RATE,

    ROUND(
        r.AMOUNT * r.CURRENCY_RATE,
        2
    ) AS BASE_AMOUNT_USD,

    ROUND(
        (r.AMOUNT * r.CURRENCY_RATE) - r.FEE,
        2
    ) AS NET_TRANSFER_VAL

FROM RAW_WIRE_TRANSFERS r

INNER JOIN DIM_WIRE_ATTRIBUTES d
    ON r.AUTH_METHOD = d.AUTH_METHOD
   AND r.RISK_FLAG = d.RISK_FLAG
   AND r.TRANSFER_TYPE = d.TRANSFER_TYPE;


 --VALIDATE TASK 2

SELECT
    TXN_ID,
    ATTRIBUTE_SK,
    AMOUNT,
    FEE,
    BASE_AMOUNT_USD,
    NET_TRANSFER_VAL
FROM FACT_WIRE_TRANSFERS
ORDER BY TXN_ID;



 --TASK 3: PERIODIC SNAPSHOT FACT

CREATE OR REPLACE TABLE FACT_VAULT_CASH_SNAPSHOT
(
    SNAPSHOT_DATE       DATE,
    VAULT_ID            VARCHAR(30),
    CURRENCY_CODE       VARCHAR(10),

    OPENING_BALANCE     NUMBER(18,2),
    CLOSING_BALANCE     NUMBER(18,2),

    RESERVE_RATIO_PCT   NUMBER(10,4),

    NET_DAILY_CHANGE    NUMBER(18,2)
);

INSERT INTO FACT_VAULT_CASH_SNAPSHOT
(
    SNAPSHOT_DATE,
    VAULT_ID,
    CURRENCY_CODE,
    OPENING_BALANCE,
    CLOSING_BALANCE,
    RESERVE_RATIO_PCT,
    NET_DAILY_CHANGE
)
SELECT
    SNAPSHOT_DATE,
    VAULT_ID,
    CURRENCY_CODE,

    OPENING_BALANCE,
    CLOSING_BALANCE,

    RESERVE_RATIO_PCT,

    CLOSING_BALANCE - OPENING_BALANCE

FROM RAW_VAULT_CASH;



 --VALIDATE TASK 3


SELECT *
FROM FACT_VAULT_CASH_SNAPSHOT
ORDER BY SNAPSHOT_DATE, VAULT_ID;

 --DAILY VAULT TOTALS
SELECT
    SNAPSHOT_DATE,

    SUM(OPENING_BALANCE) AS TOTAL_OPENING_BALANCE,

    SUM(CLOSING_BALANCE) AS TOTAL_CLOSING_BALANCE

FROM FACT_VAULT_CASH_SNAPSHOT

GROUP BY SNAPSHOT_DATE

ORDER BY SNAPSHOT_DATE;


 --TASK 4: ACCUMULATING SNAPSHOT FACT


CREATE OR REPLACE TABLE FACT_CREDIT_APPROVAL_LIFECYCLE
(
    APP_ID              VARCHAR(30),

    SUBMISSION_DATE     DATE,
    UNDERWRITE_DATE     DATE,
    RISK_APPROVAL_DATE  DATE,
    DISBURSEMENT_DATE   DATE,

    UNDERWRITE_DAYS     NUMBER,
    RISK_APPROVAL_DAYS  NUMBER,
    DISBURSEMENT_DAYS   NUMBER,
    TOTAL_CYCLE_DAYS    NUMBER
);

INSERT INTO FACT_CREDIT_APPROVAL_LIFECYCLE
(
    APP_ID,
    SUBMISSION_DATE,
    UNDERWRITE_DATE,
    RISK_APPROVAL_DATE,
    DISBURSEMENT_DATE,

    UNDERWRITE_DAYS,
    RISK_APPROVAL_DAYS,
    DISBURSEMENT_DAYS,
    TOTAL_CYCLE_DAYS
)
SELECT
    APP_ID,

    SUBMISSION_DATE,
    UNDERWRITE_DATE,
    RISK_APPROVAL_DATE,
    DISBURSEMENT_DATE,

    CASE
        WHEN UNDERWRITE_DATE IS NOT NULL
        THEN DATEDIFF(
            'DAY',
            SUBMISSION_DATE,
            UNDERWRITE_DATE
        )
    END AS UNDERWRITE_DAYS,

    CASE
        WHEN UNDERWRITE_DATE IS NOT NULL
         AND RISK_APPROVAL_DATE IS NOT NULL
        THEN DATEDIFF(
            'DAY',
            UNDERWRITE_DATE,
            RISK_APPROVAL_DATE
        )
    END AS RISK_APPROVAL_DAYS,

    CASE
        WHEN RISK_APPROVAL_DATE IS NOT NULL
         AND DISBURSEMENT_DATE IS NOT NULL
        THEN DATEDIFF(
            'DAY',
            RISK_APPROVAL_DATE,
            DISBURSEMENT_DATE
        )
    END AS DISBURSEMENT_DAYS,

    CASE
        WHEN DISBURSEMENT_DATE IS NOT NULL
        THEN DATEDIFF(
            'DAY',
            SUBMISSION_DATE,
            DISBURSEMENT_DATE
        )
    END AS TOTAL_CYCLE_DAYS

FROM RAW_CREDIT_LIFECYCLES;

-- VALIDATE TASK 4
SELECT
    APP_ID,
    SUBMISSION_DATE,
    UNDERWRITE_DATE,
    RISK_APPROVAL_DATE,
    DISBURSEMENT_DATE,
    UNDERWRITE_DAYS,
    RISK_APPROVAL_DAYS,
    DISBURSEMENT_DAYS,
    TOTAL_CYCLE_DAYS
FROM FACT_CREDIT_APPROVAL_LIFECYCLE
ORDER BY APP_ID;


 --TASK 5: IDENTIFY CURRENT BOTTLENECK


SELECT
    APP_ID,
    SUBMISSION_DATE,

    CASE

        WHEN DISBURSEMENT_DATE IS NULL
         AND RISK_APPROVAL_DATE IS NOT NULL
        THEN 'AWAITING_DISBURSAL'

        WHEN RISK_APPROVAL_DATE IS NULL
         AND UNDERWRITE_DATE IS NOT NULL
        THEN 'AWAITING_RISK_AUTH'

        WHEN UNDERWRITE_DATE IS NULL
        THEN 'AWAITING_UNDERWRITE'

        ELSE 'COMPLETED'

    END AS CURRENT_BOTTLENECK

FROM FACT_CREDIT_APPROVAL_LIFECYCLE

ORDER BY APP_ID;

 --TASK 6: FACTLESS FACT TABLE


CREATE OR REPLACE TABLE FACTLESS_COMPLIANCE_AUDIT_COVERAGE
(
    AUDIT_YEAR          NUMBER(4),
    QUARTER             VARCHAR(5),
    ACCOUNT_ID          VARCHAR(30),
    AUDITOR_FIRM        VARCHAR(50),
    COMPLIANCE_STATUS   VARCHAR(30)
);

INSERT INTO FACTLESS_COMPLIANCE_AUDIT_COVERAGE
SELECT
    AUDIT_YEAR,
    QUARTER,
    ACCOUNT_ID,
    AUDITOR_FIRM,
    COMPLIANCE_STATUS
FROM RAW_AUDIT_COVERAGE;


--VALIDATE TASK 6

SELECT *
FROM FACTLESS_COMPLIANCE_AUDIT_COVERAGE
ORDER BY AUDIT_YEAR, QUARTER, ACCOUNT_ID;


 --COUNT FACTLESS EVENTS


SELECT
    COUNT(*) AS TOTAL_AUDIT_ROWS
FROM FACTLESS_COMPLIANCE_AUDIT_COVERAGE;



 --TASK 6 BUSINESS ANALYSIS:


SELECT
    f.SENDER_ACC AS ACCOUNT_ID,

    COUNT(*) AS HIGH_RISK_TXN_COUNT,

    'NEVER_AUDITED' AS COMPLIANCE_STATUS

FROM FACT_WIRE_TRANSFERS f

INNER JOIN DIM_WIRE_ATTRIBUTES d
    ON f.ATTRIBUTE_SK = d.ATTRIBUTE_SK

LEFT JOIN FACTLESS_COMPLIANCE_AUDIT_COVERAGE a
    ON f.SENDER_ACC = a.ACCOUNT_ID
   AND a.AUDIT_YEAR = 2026

WHERE d.RISK_FLAG = 'HIGH'
  AND a.ACCOUNT_ID IS NULL

GROUP BY f.SENDER_ACC

ORDER BY f.SENDER_ACC;



 --TASK 7: RISK PROFILE CROSS-ANALYSIS

SELECT
    d.RISK_FLAG,
    d.TRANSFER_TYPE,

    COUNT(*) AS TOTAL_TXNS,

    SUM(f.FEE) AS TOTAL_FEES,

    SUM(f.BASE_AMOUNT_USD) AS TOTAL_VOLUME_USD

FROM FACT_WIRE_TRANSFERS f

INNER JOIN DIM_WIRE_ATTRIBUTES d
    ON f.ATTRIBUTE_SK = d.ATTRIBUTE_SK

GROUP BY
    d.RISK_FLAG,
    d.TRANSFER_TYPE

ORDER BY
    d.RISK_FLAG,
    d.TRANSFER_TYPE;


 --TASK 8: MULTI-FACT RECONCILIATION

WITH WIRE_TOTAL AS
(
    SELECT
        SUM(BASE_AMOUNT_USD) AS TOTAL_WIRE_VOL_USD
    FROM FACT_WIRE_TRANSFERS
),

LATEST_VAULT AS
(
    SELECT
        SUM(CLOSING_BALANCE) AS VAULT_CLOSING_USD

    FROM FACT_VAULT_CASH_SNAPSHOT

    WHERE SNAPSHOT_DATE =
    (
        SELECT MAX(SNAPSHOT_DATE)
        FROM FACT_VAULT_CASH_SNAPSHOT
    )
),

COMPLETED_LOANS AS
(
    SELECT
        COUNT(*) AS COMPLETED_LOAN_APPS

    FROM FACT_CREDIT_APPROVAL_LIFECYCLE

    WHERE DISBURSEMENT_DATE IS NOT NULL
)

SELECT
    w.TOTAL_WIRE_VOL_USD,

    v.VAULT_CLOSING_USD,

    l.COMPLETED_LOAN_APPS,

    CASE

        WHEN w.TOTAL_WIRE_VOL_USD = 2286500.00
         AND v.VAULT_CLOSING_USD = 16400000.00
         AND l.COMPLETED_LOAN_APPS = 2

        THEN TRUE

        ELSE FALSE

    END AS AUDIT_SANITY_FLAG

FROM WIRE_TOTAL w

CROSS JOIN LATEST_VAULT v

CROSS JOIN COMPLETED_LOANS l;


